### ISSUE TITLE
地图区块保存出错

### ISSUE THREAD

**Issue by Ghost-chu** [Luohuayu/CatServer#1]
```
[18:28:07] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1805) ~[rw.class:?]
at net.minecraft.entity.Entity.func_70039_c(Entity.java:1697) ~[rw.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:359) ~[atj.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:176) [atj.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:295) [lr.class:?]
at net.minecraft.world.gen.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:406) [lr.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:361) [lr.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:240) [ls.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:797) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:443) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:696) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:553) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Integer
at net.minecraft.entity.EntityAreaEffectCloud.func_189735_o(EntityAreaEffectCloud.java:179) ~[ru.class:?]
at net.minecraft.entity.EntityAreaEffectCloud.func_70014_b(EntityAreaEffectCloud.java:513) ~[ru.class:?]
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1776) ~[rw.class:?]
... 12 more
```

**Comment by Luohuayu** [comment]
报错在什么情况下出现?

**Comment by Ghost-chu** [comment]
去末地打龙时

**Comment by Luohuayu** [comment]
1.0.3已修复
