### ISSUE TITLE
疑似cat端内部的错误导致的崩服

### ISSUE THREAD

**Issue by wanli-Inaba** [Luohuayu/CatServer#11]
java.lang.ArrayIndexOutOfBoundsException: -1
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap.fixPointers(Int2ObjectLinkedOpenHashMap.java:962)
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap.removeEntry(Int2ObjectLinkedOpenHashMap.java:335)
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap.remove(Int2ObjectLinkedOpenHashMap.java:457)
	at catserver.server.utils.Int2ObjCached.removeCache(Int2ObjCached.java:21)
	at net.minecraft.world.chunk.Chunk$1.remove(Chunk.java:161)
	at net.minecraft.world.chunk.Chunk$1.remove(Chunk.java:131)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:937)
	at net.minecraft.world.World.func_175625_s(World.java:2757)
	at net.minecraft.world.WorldServer.func_175625_s(WorldServer.java:257)
	at net.minecraft.block.BlockPistonMoving.func_180663_b(BlockPistonMoving.java:56)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:662)
	at net.minecraft.world.World.func_180501_a(World.java:508)
	at net.minecraft.tileentity.TileEntityPiston.func_73660_a(TileEntityPiston.java:337)
	at net.minecraft.world.World.func_72939_s(World.java:2165)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:747)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:935)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:469)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:804)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

**Comment by Luohuayu** [comment]
可能是异步导致的问题,请尝试更换稳定版
