### ISSUE TITLE
Incompatibility Issue

### ISSUE THREAD

**Issue by Arasple** [Luohuayu/CatServer#112]
https://github.com/Bkm016/TabooLib/issues/37

Is there anything you can do about this please?

**Comment by Luohuayu** [comment]
插件没有详细说明, 已测试可以正常加载, 请提供更多信息

**Comment by Arasple** [comment]
TabooLib 能正常加载，但是其依赖包（plugins\TabooLib\libs）不能
如果插件用 @Dependency 工具注解，会有以下报错

```
[16:02:17] [Server thread/WARN]: java.lang.NoSuchFieldException: ucp
[16:02:17] [Server thread/WARN]:        at java.lang.Class.getDeclaredField(Unknown Source)
[16:02:17] [Server thread/WARN]:        at catserver.server.remapper.ReflectionMethods.getDeclaredField(ReflectionMethods.java:36)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.module.dependency.TDependencyLoader.addToPath(TDependencyLoader.java:23)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.module.dependency.TDependencyLoader.addToPath(TDependencyLoader.java:35)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.module.dependency.TDependency.requestLib(TDependency.java:45)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.module.dependency.DependencyAnnotationVisitor.visitEnd(DependencyAnnotationVisitor.java:60)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.internal.asm.ClassReader.readElementValues(ClassReader.java:2764)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.internal.asm.ClassReader.readElementValue(ClassReader.java:2847)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.internal.asm.ClassReader.readElementValues(ClassReader.java:2760)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.internal.asm.ClassReader.readElementValue(ClassReader.java:2934)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.internal.asm.ClassReader.readElementValues(ClassReader.java:2754)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.internal.asm.ClassReader.accept(ClassReader.java:563)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.internal.asm.ClassReader.accept(ClassReader.java:391)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.module.dependency.TDependencyInjector.inject(TDependencyInjector.java:22)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader$1.onLoading(PluginLoader.java:37)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader.lambda$load$0(PluginLoader.java:113)
[16:02:17] [Server thread/WARN]:        at java.util.ArrayList.forEach(Unknown Source)
[16:02:17] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader.load(PluginLoader.java:113)
```

**Comment by Luohuayu** [comment]
编译测试下:
https://github.com/Luohuayu/TabooLib/commit/a922669c24e257b33e29e0c22515e0c00a8c7b74

**Comment by Arasple** [comment]
已修复，感谢
