### ISSUE TITLE
CoreProtect not working,cannot use /co rollback

### ISSUE THREAD

**Issue by WiseRomu** [Luohuayu/CatServer#120]
Running on CatServer 1.12.2-3413a60 universal.
Whenever I use /co rollback command to rollback blocks, nothing happens and the message shows that 0 chunk(s) have been changed. Then a bug report will be shown on server console. I will paste it below. 
[18:48:10] [Thread-109/WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such index: block_index)
[18:48:10] [Thread-109/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:909)
[18:48:10] [Thread-109/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:921)
[18:48:10] [Thread-109/WARN]: at org.sqlite.core.DB.throwex(DB.java:886)
[18:48:10] [Thread-109/WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[18:48:10] [Thread-109/WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
[18:48:10] [Thread-109/WARN]: at org.sqlite.core.DB.prepare(DB.java:227)
[18:48:10] [Thread-109/WARN]: at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:81)
[18:48:10] [Thread-109/WARN]: at net.coreprotect.database.Lookup.rawLookupResultSet(Lookup.java:2046)
[18:48:10] [Thread-109/WARN]: at net.coreprotect.database.Lookup.performLookupRaw(Lookup.java:838)
[18:48:10] [Thread-109/WARN]: at net.coreprotect.database.Lookup.performRollbackRestore(Lookup.java:934)
[18:48:10] [Thread-109/WARN]: at net.coreprotect.command.RollbackRestoreCommand$1BasicThread2.run(RollbackRestoreCommand.java:350)
[18:48:10] [Thread-109/WARN]: at java.lang.Thread.run(Thread.java:748)
[18:48:10] [Thread-109/WARN]: java.lang.NullPointerException
[18:48:10] [Thread-109/WARN]: at net.coreprotect.database.Lookup.performLookupRaw(Lookup.java:839)
[18:48:10] [Thread-109/WARN]: at net.coreprotect.database.Lookup.performRollbackRestore(Lookup.java:934)
[18:48:10] [Thread-109/WARN]: at net.coreprotect.command.RollbackRestoreCommand$1BasicThread2.run(RollbackRestoreCommand.java:350)
[18:48:10] [Thread-109/WARN]: at java.lang.Thread.run(Thread.java:748)
By the way, CoreProtect v2.14.2 works on Spigot 1.12.2. Only the rollback system is not working on CatServer.
Thx~

**Comment by DerpDays** [comment]
This looks like an issue to do with your database for coreprotect, i would advise asking in their support discord [here](https://discord.gg/b4DZ4jy) or maybe try recreating your database.

**Comment by alex450** [comment]
boi, rolling back mods blocks is supported now
in the newest release
