### ISSUE TITLE
启动后炸服。。

### ISSUE THREAD

**Issue by QyInvoLing** [Luohuayu/CatServer#126]
WARNING: coremods are present:
  CorePlugin (AcademyCraft-1.1.2.jar)
  MixinLoaderForge (ValkyrienSkies-1.12.2-1.0-alpha-1.jar)
  AnotherCommonBugFix (AnotherCommonBugFix-1.0.7-1.12.2.jar)

java.lang.NoSuchFieldError: world
	at net.minecraft.world.World.<init>(World.java:179)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:359)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602)
	at java.lang.Thread.run(Unknown Source)

**Comment by Luohuayu** [comment]
与ValkyrienSkies不兼容
