### ISSUE TITLE
Crackshot error

### ISSUE THREAD

**Issue by QyInvoLing** [Luohuayu/CatServer#128]
[19:23:01] [Server thread/WARN]: [CrackShot] Task #715 for CrackShot v0.98.9 generated an exception
java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to net.minecraft.entity.EntityLiving
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftProjectile.setShooter(CraftProjectile.java:21) ~[CraftProjectile.class:git-CatServerAsync-1.12.2-cf8256a]
        at com.shampaggon.crackshot.CSDirector$4.run(CSDirector.java:2194) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServerAsync-1.12.2-cf8256a]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServerAsync-1.12.2-cf8256a]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:838) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
>

**Comment by Luohuayu** [comment]
Fixed
