### ISSUE TITLE
Double click in wb makes items disappear

### ISSUE THREAD

**Issue by QyInvoLing** [Luohuayu/CatServer#130]
Select 64x iron ingots and put the shape of a cauldron
Then keep clicking the top-right corner ingot
64x→2x

[13:14:11] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 8, Size: 7
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(Util.java:51) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.IndexOutOfBoundsException: Index: 8, Size: 7
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_181]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.NonNullList.get(NonNullList.java:52) ~[fi.class:?]
	at net.minecraft.item.crafting.ShapedRecipes.func_77573_a(ShapedRecipes.java:117) ~[akw.class:?]
	at net.minecraft.item.crafting.ShapedRecipes.func_77569_a(ShapedRecipes.java:88) ~[akw.class:?]
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:215) ~[aku.class:?]
	at net.minecraft.inventory.Container.func_192389_a(Container.java:930) ~[afr.class:?]
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(ContainerWorkbench.java:60) ~[afz.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70298_a(InventoryCrafting.java:137) ~[afy.class:?]
	at net.minecraft.inventory.Slot.func_75209_a(Slot.java:98) ~[agr.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:424) ~[afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2121) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(Util.java:50) ~[h.class:?]
	... 5 more

**Comment by Luohuayu** [comment]
The issues caused by MOD
