### ISSUE TITLE
不支援librarianlib, justenoughids,(不是崩潰 所以沒有crash log),  forestry

### ISSUE THREAD

**Issue by Jacky10X** [Luohuayu/CatServer#132]
版本是CatServer-264808e-async 

如果安裝了librarianlib, 所有人都不能進何服器
錯誤是
HandshakeMessageHandler exception
java.lang.VerifyError: JVMVRFY012 堆疊形狀不一致；類別=net/minecraft/network/NetHandlerPlayServer、方法=func_147340_a(Lnet/minecraft/network/play/client/CPacketUseEntity;)V、pc=324；類型不符，簽章 org/bukkit/plugin/PluginManager.callEvent:(Lorg/bukkit/event/Event;)V 中的引數 0 不符

如果安裝了justenoughids, 只要進了何服器 點了物品庫會彈出遊戲 
(我估計是justenoughids 是把1.12.2的chunk格式換成1.13的原因導致)
錯誤是
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/7 (CPacketClickWindow) was larger than I expected, found 1 bytes extra whilst reading packet 7

**Comment by Luohuayu** [comment]
librarianlib使用ASM修改服务端, 无法兼容
实测justenoughids没问题, 请排除其他MOD

**Comment by Jacky10X** [comment]
對不起 打擾你
剛剛玩林業模組的時候好像都有出錯:
Description: Ticking block entity
java.lang.NullPointerException: Ticking block entity
	at forestry.apiculture.BeekeepingLogic.tickBreed(BeekeepingLogic.java:380)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:251)
	at forestry.apiculture.tiles.TileBeeHousingBase.updateServerSide(TileBeeHousingBase.java:177)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:99)
	at net.minecraft.world.World.func_72939_s(World.java:2169)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:913)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:821)


至於jeid 應該可能是版本問題 (有可能是用了測試版的關係)

**Comment by Luohuayu** [comment]
应该是forestry自身问题

**Comment by Jacky10X** [comment]
好的 感謝回答
