### ISSUE TITLE
玩家登录直接崩溃

### ISSUE THREAD

**Issue by DnoYT** [Luohuayu/CatServer#134]
Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@8943409:
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.remove(Unknown Source) ~[?:1.8.0_131]
        at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:316) ~[EnergyGridCache.class:?]
        at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248) ~[EnergyGridCache.class:?]
        at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:199) ~[EnergyGridCache.class:?]
        at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
        at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
        at appeng.hooks.TickHandler.onTick(TickHandler.java:228) ~[TickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_214_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-2019-11-27]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:221) [EventBus.class:git-CatServer-1.12.2-2019-11-27]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:263) [FMLCommonHandler.class:git-CatServer-1.12.2-2019-11-27]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:850) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[05:51:49] [Server thread/ERROR]: Index: 6 Listeners:
[05:51:49] [Server thread/ERROR]: 0: NORMAL
[05:51:49] [Server thread/ERROR]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@7a000773 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[05:51:49] [Server thread/ERROR]: 2: ASM: ic2.core.TickHandler@5d98c9de onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[05:51:49] [Server thread/ERROR]: 3: ASM: class buildcraft.lib.BCLibEventDist serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[05:51:49] [Server thread/ERROR]: 4: ASM: INSTANCE onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[05:51:49] [Server thread/ERROR]: 5: ASM: com.creativemd.creativecore.common.event.CreativeTickHandler@3ad1072 onEventTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[05:51:49] [Server thread/ERROR]: 6: ASM: appeng.hooks.TickHandler@563afe06 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[05:51:49] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.remove(Unknown Source) ~[?:1.8.0_131]
        at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:316) ~[EnergyGridCache.class:?]
        at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248) ~[EnergyGridCache.class:?]
        at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:199) ~[EnergyGridCache.class:?]
        at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
        at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
        at appeng.hooks.TickHandler.onTick(TickHandler.java:228) ~[TickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_214_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-2019-11-27]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:221) ~[EventBus.class:git-CatServer-1.12.2-2019-11-27]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:263) ~[FMLCommonHandler.class:git-CatServer-1.12.2-2019-11-27]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:850) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[05:51:49] [Server thread/ERROR]: This crash report has been saved to: E:\我的世界\服务器\模组服M端\.\crash-reports\crash-2020-03-06_05.51.49-server.txt

**Comment by Luohuayu** [comment]
请向AE Mod作者反馈
