### ISSUE TITLE
Crash when crop grows

### ISSUE THREAD

**Issue by QyInvoLing** [Luohuayu/CatServer#137]
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=moisture, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=minecraft:sand, properties=[variant]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at ic2.core.crop.TileEntityCrop.updateTerrainHumidity(TileEntityCrop.java:621)
	at ic2.core.crop.TileEntityCrop.performTick(TileEntityCrop.java:232)
	at ic2.core.crop.TileEntityCrop.updateEntityServer(TileEntityCrop.java:200)
	at ic2.core.block.TileEntityBlock.func_73660_a(TileEntityBlock.java:326)
	at net.minecraft.world.World.func_72939_s(World.java:2169)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:913)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Unknown Source)

**Comment by Luohuayu** [comment]
Not a catserver issues
