### ISSUE TITLE
FAWE

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#166]
I use:
- WorldEditForge: https://www.curseforge.com/minecraft/mc-mods/worldedit/files/2655056
- FAWE: FastAsyncWorldEdit-forge112-19.11.13-5505943-1282-22.3.5.jar or other
https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/

Most of the territory is not updated chunks
Syncing with the client also works poorly
SCREEN: https://ibb.co/WPqCpq9

I note that this CatServer version works stably with FAWE: CatServer-git-ce5a5e8-Community.jar

Log Mod version:
```[10:06:29] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: day-d issued server command: //set 0
[10:06:29] [Server thread/WARN] []: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: The async thread call sync loadChunk method, it will crash the server! Please report to MOD or plugin author!
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinTask.get(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:185)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:220)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.forge.ForgeTaskMan$1.run(ForgeTaskMan.java:47)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.forge.ForgeTaskMan$3.run(ForgeTaskMan.java:131)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.forge.ForgeTaskMan.onServerTick(ForgeTaskMan.java:72)
[10:06:29] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_ForgeTaskMan_onServerTick_ServerTickEvent.invoke(.dynamic)
[10:06:29] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[10:06:29] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
[10:06:29] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:281)
[10:06:29] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:771)
[10:06:29] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636)
[10:06:29] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)
[10:06:29] [Server thread/WARN] []: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: The async thread call sync loadChunk method, it will crash the server! Please report to MOD or plugin author!
[10:06:29] [Server thread/WARN] []: 	at sun.reflect.GeneratedConstructorAccessor72.newInstance(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	... 14 more
[10:06:29] [Server thread/WARN] []: Caused by: java.lang.RuntimeException: The async thread call sync loadChunk method, it will crash the server! Please report to MOD or plugin author!
[10:06:29] [Server thread/WARN] []: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:62)
[10:06:29] [Server thread/WARN] []: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:125)
[10:06:29] [Server thread/WARN] []: 	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:96)
[10:06:29] [Server thread/WARN] []: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:142)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.forge.v112.ForgeChunk_All.getNewChunk(ForgeChunk_All.java:126)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.forge.v112.ForgeChunk_All.getNewChunk(ForgeChunk_All.java:40)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.example.CharFaweChunk.getChunk(CharFaweChunk.java:56)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.forge.v112.ForgeChunk_All.call(ForgeChunk_All.java:158)
[10:06:29] [Server thread/WARN] []: 	at com.boydti.fawe.forge.v112.ForgeChunk_All.call(ForgeChunk_All.java:40)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[10:06:29] [Server thread/WARN] []: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ```
```

Log Plugin version:
```
[10:56:44] [Server thread/WARN] []: java.lang.NoSuchMethodError: net.minecraft.world.gen.ChunkProviderServer.getChunkAt(IILjava/lang/Runnable;Z)Lnet/minecraft/world/chunk/Chunk;
[10:56:44] [Server thread/WARN] []: 	at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.loadChunk(BukkitQueue_1_12.java:182)
[10:56:44] [Server thread/WARN] []: 	at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.loadChunk(BukkitQueue_1_12.java:51)
[10:56:44] [Server thread/WARN] []: 	at com.boydti.fawe.example.MappedFaweQueue$1.run(MappedFaweQueue.java:64)
[10:56:44] [Server thread/WARN] []: 	at com.boydti.fawe.example.MappedFaweQueue$1.run(MappedFaweQueue.java:56)
[10:56:44] [Server thread/WARN] []: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[10:56:44] [Server thread/WARN] []: 	at com.boydti.fawe.util.TaskManager$3.run(TaskManager.java:348)
[10:56:44] [Server thread/WARN] []: 	at com.boydti.fawe.util.TaskManager$3.run(TaskManager.java:344)
[10:56:44] [Server thread/WARN] []: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[10:56:44] [Server thread/WARN] []: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:124)
[10:56:44] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[10:56:44] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421)
[10:56:44] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:837)
[10:56:44] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[10:56:44] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
[10:56:44] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636)
[10:56:44] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by Luohuayu** [comment]
Async load chunk will crash the server, the operation is not allowed in catsever. Please report to plugin author

**Comment by day-d** [comment]
LOL
`I note that this CatServer version works stably with FAWE: CatServer-git-ce5a5e8-Community.jar`
See?
Can I send you a video? The mod works fine on the old version CatServer.

**Comment by dayd21git** [comment]
> Async load chunk will crash the server, the operation is not allowed in catsever. Please report to plugin author

LOL
`I note that this CatServer version works stably with FAWE: CatServer-git-ce5a5e8-Community.jar`
See?
Can I send you a video? The mod works fine on the old version CatServer.
