### ISSUE TITLE
Orebfuscator and Protocollib - Errors

### ISSUE THREAD

**Issue by regix1** [Luohuayu/CatServer#187]
I'm having trouble with both of these plugins. 
I'm using the latest version of both plugins.
Links: 
[Protocollib](https://www.spigotmc.org/resources/protocollib.1997/)
[Orebfuscator](https://www.spigotmc.org/resources/orebfuscator.22818/)

Protocollib: throws errors with certain mods when they are installed
Orebfuscator: If you install Orebfuscator, the required mod is Protocollib and it prevents you from joining the server entirely. 

If this is too big of an issue to fix that's understandable but I just wanted to let you know. 

**Protocollib error **without** Orebfuscator installed:**
`[17:45:22] [Server thread/WARN]: [ProtocolLib] If you're getting this error for other reasons, please report it!
[17:45:22] [Server thread/WARN]: java.lang.ExceptionInInitializerError
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.cloning.BukkitCloner.fromWrapper(BukkitCloner.java:46)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.cloning.BukkitCloner.<clinit>(BukkitCloner.java:85)
[17:45:22] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:45:22] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[17:45:22] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[17:45:22] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.instances.DefaultInstances.createInstance(DefaultInstances.java:332)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.instances.DefaultInstances.getDefaultInternal(DefaultInstances.java:292)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.instances.DefaultInstances.getDefault(DefaultInstances.java:165)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.instances.DefaultInstances.create(DefaultInstances.java:350)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.cloning.AggregateCloner$Builder$1.apply(AggregateCloner.java:108)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.cloning.AggregateCloner$Builder$1.apply(AggregateCloner.java:105)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.cloning.AggregateCloner$Builder.build(AggregateCloner.java:153)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.reflect.cloning.AggregateCloner.<clinit>(AggregateCloner.java:179)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.events.PacketContainer.<clinit>(PacketContainer.java:86)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:297)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[17:45:22] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[17:45:22] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198)
[17:45:22] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149)
[17:45:22] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336)
[17:45:22] [Server thread/WARN]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214)
[17:45:22] [Server thread/WARN]:        at net.minecraft.world.WorldServer.func_184159_a(WorldServer.java:1569)
[17:45:22] [Server thread/WARN]:        at net.minecraft.world.WorldServer.sendParticles(WorldServer.java:1552)
[17:45:22] [Server thread/WARN]:        at net.minecraft.world.WorldServer.func_180505_a(WorldServer.java:1541)
[17:45:22] [Server thread/WARN]:        at net.minecraft.world.WorldServer.func_175739_a(WorldServer.java:1535)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:255)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.Entity.move0(Entity.java:1086)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.Entity.func_70091_d(Entity.java:741)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:2282)
[17:45:22] [Server thread/WARN]:        at drzhark.mocreatures.entity.MoCEntityAnimal.func_191986_a(MoCEntityAnimal.java:688)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2723)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:622)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:207)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.passive.EntityAnimal.func_70636_d(EntityAnimal.java:46)
[17:45:22] [Server thread/WARN]:        at drzhark.mocreatures.entity.MoCEntityAnimal.func_70636_d(MoCEntityAnimal.java:359)
[17:45:22] [Server thread/WARN]:        at drzhark.mocreatures.entity.MoCEntityTameableAnimal.func_70636_d(MoCEntityTameableAnimal.java:435)
[17:45:22] [Server thread/WARN]:        at drzhark.mocreatures.entity.passive.MoCEntityBird.func_70636_d(MoCEntityBird.java:327)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2505)
[17:45:22] [Server thread/WARN]:        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:331)
[17:45:22] [Server thread/WARN]:        at drzhark.mocreatures.entity.passive.MoCEntityBird.func_70071_h_(MoCEntityBird.java:406)
[17:45:22] [Server thread/WARN]:        at net.minecraft.world.World.func_72866_a(World.java:2354)
[17:45:22] [Server thread/WARN]:        at net.minecraft.world.World.func_72870_g(World.java:2308)
[17:45:22] [Server thread/WARN]:        at net.minecraft.world.World.func_72939_s(World.java:2066)
[17:45:22] [Server thread/WARN]:        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742)
[17:45:22] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:913)
[17:45:22] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473)
[17:45:22] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)
[17:45:22] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[17:45:22] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[17:45:22] [Server thread/WARN]: Caused by: java.lang.NullPointerException`

****Both** Protocollib and Orebfuscator Installed Error:**
`[17:49:38] [Server thread/INFO]: Regix lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ExceptionInInitializerError`

**Comment by regix1** [comment]
I opened an issue/feature request with ProtocolLib.
If anyone is interested to see if this issue will be fixed.

https://github.com/dmulloy2/ProtocolLib/issues/825

**Comment by adsa562** [comment]
Maybe you can try to use older version for ProtocolLib (ex:4.3.0) and Orebfuscator (ex:4.4.1) to avoid this problem.

**Comment by regix1** [comment]
> Maybe you can try to use older version for ProtocolLib (ex:4.3.0) and Orebfuscator (ex:4.4.1) to avoid this problem.

I appreciate the reply, I have tried this already and it didn't work. The current Owner/Dev of ProtocolLib is working on a Fix. He just released a fix, but CatServer wont Receive Packets so hopefully something can be done.
