### ISSUE TITLE
使用DungeonsXL出现报错。

### ISSUE THREAD

**Issue by KonjacCool** [Luohuayu/CatServer#190]
报错内容如下.

[Server thread/WARN]: [DungeonsXL] Task #31827 for DungeonsXL v0.18-SNAPSHOT-958 generated an exception
java.lang.NullPointerException: null
at de.erethon.commons.misc.FileUtil.copyDir(FileUtil.java:77) ~[?:?]
at de.erethon.dungeonsxl.world.DEditWorld$1.onFinish(DEditWorld.java:116) ~[?:?]
at de.erethon.commons.misc.ProgressBar.run(ProgressBar.java:81) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-2fbf24f]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-2fbf24f]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:830) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]

**Comment by Luohuayu** [comment]
无法兼容该插件
