### ISSUE TITLE
This is not a but only some info

### ISSUE THREAD

**Issue by pwall2222** [Luohuayu/CatServer#192]
`[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:233)
        at jline.UnixTerminal.<init>(UnixTerminal.java:64)
        at jline.UnixTerminal.<init>(UnixTerminal.java:49)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at jline.TerminalFactory.getFlavor(TerminalFactory.java:209)
        at jline.TerminalFactory.create(TerminalFactory.java:100)
        at jline.TerminalFactory.get(TerminalFactory.java:184)
        at jline.TerminalFactory.get(TerminalFactory.java:190)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:240)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:232)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:224)
        at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:212)
        at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:79)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1641)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at catserver.server.CatServerLaunch.main(CatServerLaunch.java:11)
[05:26:41] [main/ERROR]: Failed to transform class: net.minecraft.item.ItemBucket                                            
java.lang.NullPointerException: null                                                                                         
        at com.therandomlabs.randompatches.patch.ItemBucketPatch.apply(ItemBucketPatch.java:35) ~[ItemBucketPatch.class:?]   
        at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.21.0.3-1.12.2
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:25
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]    
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_252]                                               
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_252]                                               
        at net.minecraft.item.Item.func_150900_l(Item.java:1598) [ain.class:?]                                               
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:780) [ni.class:?]                                       
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1633) [MinecraftServer.class:?]                    
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]                                        
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]                      
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]              
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]                                                   
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]                             
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]                                
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]                                        
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]                      
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]              
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]                                                   
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [CatServer-1.12.2.jar:git-C
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [CatServer-1.12.2.jar:git-
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]                                        
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]                      
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]              
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]                                                   
        at catserver.server.CatServerLaunch.main(CatServerLaunch.java:11) [CatServer-1.12.2.jar:git-CatServer-1.12.2-2fbf24f]
[05:26:51] [Server thread/ERROR]: Failed to transform class: net.minecraft.network.NetHandlerPlayServer
java.lang.NullPointerException: null
        at org.objectweb.asm.tree.InsnList.insert(InsnList.java:347) ~[asm-debug-all-5.2.jar:5.2]
        at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.patchUpdate(NetHandlerPlayServerPatch.java:121) ~[NetHandlerPlayServerPatch.class:?]
        at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.apply(NetHandlerPlayServerPatch.java:26) ~[NetHandlerPlayServerPatch.class:?]
        at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.21.0.3-1.12.2.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) [ASMTransformerWrapper$TransformerWrapper.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_252]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_252]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_252]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_252]
        at java.lang.Class.privateGetPublicMethods(Class.java:2902) [?:1.8.0_252]
        at java.lang.Class.getMethods(Class.java:1615) [?:1.8.0_252]
        at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:84) [EventBus.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) [AutomaticEventSubscriber.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611) [FMLModContainer.class:git-CatServer-1.12.2-2fbf24f]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:git-CatServer-1.12.2-2fbf24f]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595) [Loader.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335) [FMLCommonHandler.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`
All warnings the server does when i inicialite it... Only info, the server works wonderfully tho.

**Comment by Luohuayu** [comment]
Some Linux will cause jline initialize error, the warning can be ignored if server works

**Comment by Luohuayu** [comment]
jline is not necessary
