### ISSUE TITLE
[CMI] Unhandled exception occured in onPacketSending(PacketEvent) for CMI

### ISSUE THREAD

**Issue by ghost** [Luohuayu/CatServer#207]
[CMI] Unhandled exception occured in onPacketSending(PacketEvent) for CMI
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.5.1]
        at com.Zrips.CMI.AllListeners.ProtocolEvent$1.onPacketSending(ProtocolEvent.java:71) ~[CMI8.6.27.0.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.5.1]
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198) [gw.class:?]
        at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149) [gw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214) [NetworkDispatcher$1.class:git-CatServer-1.12.2-5fd7768]
        at net.minecraft.entity.player.EntityPlayerMP.func_71033_a(EntityPlayerMP.java:1513) [oq.class:?]
        at net.minecraft.command.CommandGameMode.func_184881_a(CommandGameMode.java:43) [ck.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:125) [VanillaCommandWrapper.class:git-CatServer-1.12.2-5fd7768]
        at org.bukkit.craftbukkit.v1_12_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:54) [VanillaCommandWrapper.class:git-CatServer-1.12.2-5fd7768]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) [SimpleCommandMap.class:git-CatServer-1.12.2-5fd7768]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:709) [CraftServer.class:git-CatServer-1.12.2-5fd7768]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[07:33:55] [Server thread/ERROR]: Parameters:
  net.minecraft.network.play.server.SPacketChangeGameState@5356415d[
    field_149140_b=3
    field_149141_c=1.0
  ]

This only happens on catserver not on Magmaserver.

**Comment by Luohuayu** [comment]
Use ProtocolLib version 4.3.0
