### ISSUE TITLE
Erroring while backup and mod loading.

### ISSUE THREAD

**Issue by TheDarkDnKTv** [Luohuayu/CatServer#21]
`[23:34:39] [Server thread/ERROR] [malisiscore]: [ChunkCollisionTransformer] The instruction list was not found in net.minecraft.network.NetHandlerPlayServer:func_147345_a(Lnet/minecraft/network/play/client/CPacketPlayerDigging;)V
Exception in thread "pool-2-thread-7" org.apache.commons.lang.UnhandledException: Plugin SaveIt v1.1.7 generated an exception while executing task 8
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:62)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at me.dretax.SaveIt.metrics.Metrics.postPlugin(Metrics.java:325)
at me.dretax.SaveIt.metrics.Metrics.access$400(Metrics.java:47)
at me.dretax.SaveIt.metrics.Metrics$1.run(Metrics.java:213)
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:70)
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
... 3 more`

**Comment by TheDarkDnKTv** [comment]
Thanks, yea it really for old bukkit version. I will try to other plugins. Thank you for your every day work.
