### ISSUE TITLE
BUG: Players cannot log in when adding too many mods.

### ISSUE THREAD

**Issue by MinuteSphinx** [Luohuayu/CatServer#214]
That happens when the number of mods exceeds about 92 or higher.
the log is below:

`[13:11:50] [User Authenticator #1/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: UUID of player MinuteSphinx is 8fd3a311-a3ce-30cc-8a8f-ea8fc390eb65
[13:11:51] [Server thread/TRACE] [FML]: Handshake channel activating
[13:11:51] [Server thread/DEBUG] [FML]: FMLHandshakeServerState: null->FMLHandshakeServerState$1:START
[13:11:51] [Server thread/DEBUG] [FML]:   Next: HELLO
[13:11:51] [Server thread/ERROR] [FML]: HandshakeMessageHandler exception
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/network/NetHandlerPlayServer.func_147351_a(Lnet/minecraft/network/play/client/CPacketClickWindow;)V @180: invokestatic
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'org/bukkit/inventory/InventoryView'
  Current Frame:
    bci: @180
    flags: { }
    locals: { 'net/minecraft/network/NetHandlerPlayServer', 'net/minecraft/network/play/client/CPacketClickWindow', integer, 'java/lang/Object' }
    stack: { 'java/lang/Object', integer }
  Bytecode:
    0x0000000: 2b2a 2ab4 00e1 b602 1cb8 0222 2ab4 00e1
    0x0000010: b603 3e99 0004 b12a b400 e1b6 019d 2ab4
    0x0000020: 00e1 b409 42b4 09bf 2bb6 09c4 a008 f32a
    0x0000030: b400 e1b4 0942 2ab4 00e1 b609 c899 08e2
    0x0000040: 2ab4 00e1 b409 422a b400 e1b6 09cb 9908
    0x0000050: d12a b400 e1b6 04ec 3d2b b609 ce02 a200
    0x0000060: 0e2b b609 ce11 fc19 9f00 04b1 2ab4 00e1
    0x0000070: b409 42b6 09d2 4e2d c700 37bb 09d4 592a
    0x0000080: b400 e1b6 00f2 b809 d7b4 00e9 2ab4 00e1
    0x0000090: b600 f2b2 09da b609 de2a b400 e1b4 0942
    0x00000a0: b709 e14e 2ab4 00e1 b409 422d b609 e52d
    0x00000b0: 2bb6 09ce b809 e93a 04b2 09ee 3a05 b209
    0x00000c0: f33a 06b2 09f6 3a07 b209 f92b b609 fdb6
    0x00000d0: 0a00 2eaa 0000 051c 0000 0001 0000 0007
    0x00000e0: 0000 0029 0000 0210 0000 0283 0000 033b
    0x00000f0: 0000 03b1 0000 0495 0000 04b4 2bb6 0a03
    0x0000100: 9a00 0bb2 0a06 3a05 a700 102b b60a 0304
    0x0000110: a000 08b2 0a09 3a05 2bb6 0a03 9900 0b2b
    0x0000120: b60a 0304 a004 cbb2 0a0c 3a06 2bb6 09ce
    0x0000130: 11fc 19a0 0028 2ab4 00e1 b405 62b6 0a0f
    0x0000140: b606 149a 04ac 2bb6 0a03 9a00 09b2 0a12
    0x0000150: a700 06b2 0a15 3a06 a704 972b b609 ce9c
    0x0000160: 000b b20a 0c3a 06a7 0488 2ab4 00e1 b409
    0x0000170: 422b b609 ceb6 0a19 3a08 1908 c601 6419
    0x0000180: 08b6 0a1e 3a09 2ab4 00e1 b405 62b6 0a0f
    0x0000190: 3a0a 1909 b606 1499 0020 190a b606 149a
    0x00001a0: 0141 2bb6 0a03 9a00 09b2 0a21 a700 06b2
    0x00001b0: 0a24 3a06 a701 2c19 082a b400 e1b6 0a27
    0x00001c0: 9901 2019 0ab6 0614 9900 182b b60a 039a
    0x00001d0: 0009 b20a 2aa7 0006 b20a 2d3a 06a7 0103
    0x00001e0: 1908 190a b60a 3099 00ad 1909 190a b60a
    0x00001f0: 3399 008e 1909 190a b80a 3799 0084 2bb6
    0x0000200: 0a03 9a00 0b19 0ab6 093e a700 0404 360b
    0x0000210: 150b 1909 b60a 3a19 09b6 093e 64b8 0a3d
    0x0000220: 360b 150b 1908 b40a 41b9 0a46 0100 1909
    0x0000230: b609 3e64 b80a 3d36 0b15 0b04 a000 0bb2
    0x0000240: 0a24 3a06 a700 3815 0b19 0ab6 093e a000
    0x0000250: 0bb2 0a21 3a06 a700 2615 0b9c 0017 150b
    0x0000260: 029f 0009 b20a 49a7 0006 b20a 4c3a 06a7
    0x0000270: 000d 150b 9900 08b2 0a4f 3a06 a700 6419
    0x0000280: 0ab6 093e 1908 b60a 52a3 0057 b20a 553a
    0x0000290: 06a7 004f 190a b608 c919 09b6 08c9 a600
    0x00002a0: 4219 0ab6 0a58 9900 1019 0ab6 0a5b 1909
    0x00002b0: b60a 5ba0 002d 190a 1909 b80a 3799 0023
    0x00002c0: 1909 b609 3e9b 001b 1909 b609 3e19 0ab6
    0x00002d0: 093e 6019 0ab6 0a3a a300 08b2 0a2a 3a06
    0x00002e0: a703 0f2b b60a 039a 000b b20a 5e3a 05a7
    0x00002f0: 0010 2bb6 0a03 04a0 0008 b20a 613a 052b
    0x0000300: b60a 0399 000b 2bb6 0a03 04a0 02e4 2bb6
    0x0000310: 09ce 9c00 0bb2 0a0c 3a06 a702 d52a b400
    0x0000320: e1b4 0942 2bb6 09ce b60a 193a 0819 08c6
    0x0000330: 001f 1908 2ab4 00e1 b60a 2799 0013 1908
    0x0000340: b60a 6499 000b b20a 673a 06a7 0008 b20a
    0x0000350: 0c3a 06a7 029c 2bb6 0a03 9b02 952b b60a
    0x0000360: 0310 09a2 028c b20a 6a3a 052a b400 e1b4
    0x0000370: 0942 2bb6 09ce b60a 193a 0819 082a b400
    0x0000380: e1b6 0a27 9900 822a b400 e1b4 0562 2bb6
    0x0000390: 0a03 b60a 6e3a 0919 09b6 0614 9a00 1c19
    0x00003a0: 08b4 0a41 2ab4 00e1 b405 62a6 0011 1908
    0x00003b0: 1909 b60a 3099 0007 04a7 0004 0336 0a19
    0x00003c0: 08b6 0a64 9900 1815 0a99 000b b20a 713a
    0x00003d0: 06a7 0032 b20a 743a 06a7 002a 1908 b60a
    0x00003e0: 649a 001d 1909 b606 149a 0015 1908 1909
    0x00003f0: b60a 3099 000b b20a 713a 06a7 0008 b20a
    0x0000400: 0c3a 06a7 0008 b20a 0c3a 06a7 01e4 2bb6
    0x0000410: 0a03 05a0 0064 b20a 773a 052b b609 ce11
    0x0000420: fc19 a000 0bb2 0a0c 3a06 a701 c52a b400
    0x0000430: e1b4 0942 2bb6 09ce b60a 193a 0819 08c6
    0x0000440: 0030 1908 b60a 6499 0028 2ab4 00e1 b402
    0x0000450: 9cb4 0a7a 9900 1b2a b400 e1b4 0562 b60a
    0x0000460: 0fb6 0614 9900 0bb2 0a7d 3a06 a700 08b2
    0x0000470: 0a0c 3a06 a701 7bb2 09ee 3a05 b209 f33a
    0x0000480: 06a7 016e 2bb6 09ce 9b00 c62b b60a 039a
    0x0000490: 005d b20a 803a 052a b400 e1b4 0942 2bb6
    0x00004a0: 09ce b60a 193a 0819 08c6 003b 1908 b60a
    0x00004b0: 6499 0033 1908 2ab4 00e1 b60a 2799 0027
    0x00004c0: 1908 b60a 1eb6 0614 9a00 1c19 08b6 0a1e
    0x00004d0: b608 c9b2 0a86 b80a 8aa5 000b b20a 8d3a
    0x00004e0: 06a7 0008 b20a 0c3a 06a7 0106 2bb6 0a03
    0x00004f0: 04a0 00fe b20a 903a 052a b400 e1b4 0942
    0x0000500: 2bb6 09ce b60a 193a 0819 08c6 003b 1908
    0x0000510: b60a 6499 0033 1908 2ab4 00e1 b60a 2799
    0x0000520: 0027 1908 b60a 1eb6 0614 9a00 1c19 08b6
    0x0000530: 0a1e b608 c9b2 0a86 b80a 8aa5 000b b20a
    0x0000540: 933a 06a7 0008 b20a 0c3a 06a7 00a4 b20a
    0x0000550: 063a 052b b60a 0304 a000 08b2 0a09 3a05
    0x0000560: b20a 0c3a 06a7 008a 2ab4 00e1 b409 422b
    0x0000570: b609 ce2b b60a 032b b609 fd2a b400 e1b6
    0x0000580: 0a97 3a07 a700 6bb2 0a9a 3a05 b20a 0c3a
    0x0000590: 062b b609 ce9b 005a 2ab4 00e1 b405 62b6
    0x00005a0: 0a0f b606 149a 004a 2ab4 00e1 b405 62b6
    0x00005b0: 0a0f 3a08 b20a 0c3a 062d b60a a019 08b6
    0x00005c0: 08c9 b80a a4b8 0aaa b90a af02 009a 001a
    0x00005d0: 2db6 0ab2 1908 b608 c9b8 0aa4 b80a aab9
    0x00005e0: 0aaf 0200 9900 08b2 0ab5 3a06 a700 032b
    0x00005f0: b609 fdb2 0ab9 a502 3919 05b2 0a6a a600
    0x0000600: 1ebb 0abb 592d 1904 2bb6 09ce 1905 1906
    0x0000610: 2bb6 0a03 b70a be3a 0ca7 0017 bb0a bb59
    0x0000620: 2d19 042b b609 ce19 0519 06b7 0ac1 3a0c
    0x0000630: 2db6 0aa0 3a08 2bb6 09ce 9a00 5719 08c1
    0x0000640: 0ac3 9900 4f19 08c0 0ac3 b90a c701 003a
    0x0000650: 0919 09c6 003e 1905 b20a 6aa6 0020 bb0a
    0x0000660: c959 1909 2d19 042b b609 ce19 0519 062b
    0x0000670: b60a 03b7 0acc 3a0c a700 19bb 0ac9 5919
    0x0000680: 092d 1904 2bb6 09ce 1905 1906 b70a cf3a
    0x0000690: 0c19 0c1c b60a d02a b400 e1b4 0942 3a09
    0x00006a0: 2ab4 00ea b601 e819 0cb9 01ee 0200 2ab4
    0x00006b0: 00e1 b409 4219 09a5 0004 b1b2 0ad3 190c
    0x00006c0: b60a d6b6 0ad7 2eaa 0000 0152 0000 0001
    0x00006d0: 0000 0003 0000 0019 0000 0019 0000 0038
    0x00006e0: 2ab4 00e1 b409 422b b609 ce2b b60a 032b
    0x00006f0: b609 fd2a b400 e1b6 0a97 3a07 a701 1db2
    0x0000700: 0ada 1906 b60a db2e aa00 0000 0000 0110
    0x0000710: 0000 0001 0000 0013 0000 005c 0000 005c
    0x0000720: 0000 005c 0000 005c 0000 005c 0000 005c
    0x0000730: 0000 006d 0000 006d 0000 006d 0000 006d
    0x0000740: 0000 006d 0000 006d 0000 006d 0000 00bd
    0x0000750: 0000 00bd 0000 00f0 0000 00f0 0000 00f0
    0x0000760: 0000 0110 2ab4 00e1 2ab4 00e1 b409 42b6
    0x0000770: 0946 a700 a62a b400 e1b4 00e7 bb0a dd59
    0x0000780: 0202 2ab4 00e1 b405 62b6 0a0f b70a e0b6
    0x0000790: 0181 2ab4 00e1 b400 e7bb 0add 592a b400
    0x00007a0: e1b4 0942 b409 bf2b b609 ce2a b400 e1b4
    0x00007b0: 0942 2bb6 09ce b60a 19b6 0a1e b70a e0b6
    0x00007c0: 0181 a700 562a b400 e1b4 00e7 bb0a dd59
    0x00007d0: 2ab4 00e1 b409 42b4 09bf 2bb6 09ce 2ab4
    0x00007e0: 00e1 b409 422b b609 ceb6 0a19 b60a 1eb7
    0x00007f0: 0ae0 b601 81a7 0023 2ab4 00e1 b400 e7bb
    0x0000800: 0add 5902 022a b400 e1b4 0562 b60a 0fb7
    0x0000810: 0ae0 b601 81a7 0003 b119 0cc1 0ac9 9900
    0x0000820: 112a b400 e12a b400 e1b4 0942 b609 462b
    0x0000830: b60a e319 07b8 0ae6 9900 412a b400 e1b4
    0x0000840: 00e7 bb0a e859 2bb6 09c4 2bb6 0aec 04b7
    0x0000850: 0aef b601 812a b400 e104 b50a f22a b400
    0x0000860: e1b4 0942 b60a f52a b400 e1b6 0af8 2ab4
    0x0000870: 00e1 03b5 0af2 a700 a92a b400 b22a b400
    0x0000880: e1b4 0942 b409 bf2b b60a ecb8 0afd b60b
    0x0000890: 012a b400 e1b4 00e7 bb0a e859 2bb6 09c4
    0x00008a0: 2bb6 0aec 03b7 0aef b601 812a b400 e1b4
    0x00008b0: 0942 2ab4 00e1 03b6 0b05 b80b 0b3a 0803
    0x00008c0: 3609 1509 2ab4 00e1 b409 42b4 0b0e b90b
    0x00008d0: 1101 00a2 003c 2ab4 00e1 b409 42b4 0b0e
    0x00008e0: 1509 b90b 1402 00c0 0a1b b60a 1e3a 0a19
    0x00008f0: 0ab6 0614 9900 09b2 09f6 a700 0519 0a3a
    0x0000900: 0b19 0819 0bb6 0b15 5784 0901 a7ff b62a
    0x0000910: b400 e12a b400 e1b4 0942 1908 b60b 19b1
    0x0000920:                                        
  Stackmap Table:
    same_frame(@23)
    append_frame(@108,Integer)
    append_frame(@175,Object[#4])
    full_frame(@252,{Object[#2],Object[#2497],Integer,Object[#4],Object[#44],Object[#2539],Object[#2544],Object[#1452]},{})
    same_frame(@267)
    same_frame(@280)
    same_frame(@295)
    same_frame(@339)
    same_locals_1_stack_item_frame(@342,Object[#2544])
    same_frame(@347)
    same_frame(@362)
    append_frame(@431,Object[#2587],Object[#1452],Object[#1452])
    same_locals_1_stack_item_frame(@434,Object[#2544])
    same_frame(@439)
    same_frame(@472)
    same_locals_1_stack_item_frame(@475,Object[#2544])
    same_frame(@480)
    same_frame(@525)
    same_locals_1_stack_item_frame(@526,Integer)
    append_frame(@583,Integer)
    same_frame(@601)
    same_frame(@618)
    same_locals_1_stack_item_frame(@621,Object[#2544])
    same_frame(@626)
    same_frame(@636)
    chop_frame(@639,1)
    same_frame(@660)
    same_frame(@694)
    chop_frame(@736,2)
    chop_frame(@739,1)
    same_frame(@754)
    same_frame(@767)
    same_frame(@782)
    same_frame(@797)
    append_frame(@846,Object[#2587])
    same_frame(@851)
    chop_frame(@854,1)
    append_frame(@952,Object[#2587],Object[#1452])
    same_frame(@956)
    same_locals_1_stack_item_frame(@957,Integer)
    append_frame(@980,Integer)
    same_frame(@988)
    same_frame(@1022)
    same_frame(@1027)
    chop_frame(@1030,2)
    same_frame(@1035)
    chop_frame(@1038,1)
    same_frame(@1069)
    append_frame(@1135,Object[#2587])
    same_frame(@1140)
    chop_frame(@1143,1)
    same_frame(@1156)
    append_frame(@1252,Object[#2587])
    same_frame(@1257)
    chop_frame(@1260,1)
    append_frame(@1350,Object[#2587])
    same_frame(@1355)
    chop_frame(@1358,1)
    same_frame(@1376)
    same_frame(@1384)
    same_frame(@1415)
    append_frame(@1511,Object[#1452])
    same_frame(@1516)
    chop_frame(@1519,1)
    same_frame(@1564)
    full_frame(@1584,{Object[#2],Object[#2497],Integer,Object[#4],Object[#44],Object[#2539],Object[#2544],Object[#1452],Top,Top,Top,Top,Object[#2747]},{})
    full_frame(@1659,{Object[#2],Object[#2497],Integer,Object[#4],Object[#44],Object[#2539],Object[#2544],Object[#1452],Object[#2732],Object[#2870],Top,Top,Object[#2747]},{})
    full_frame(@1681,{Object[#2],Object[#2497],Integer,Object[#4],Object[#44],Object[#2539],Object[#2544],Object[#1452],Object[#2732],Top,Top,Top,Object[#4]},{})
    full_frame(@1723,{Object[#2],Object[#2497],Integer,Object[#4],Object[#44],Object[#2539],Object[#2544],Object[#1452],Object[#2732],Object[#2492],Top,Top,Object[#4]},{})
    same_frame(@1760)
    same_frame(@1791)
    same_frame_extended(@1892)
    same_frame(@1909)
    same_frame_extended(@1989)
    same_frame(@2040)
    same_frame(@2072)
    same_frame(@2073)
    full_frame(@2095,{Object[#2],Object[#2497],Integer,Object[#4],Object[#44],Object[#2539],Object[#2544],Object[#1452]},{})
    same_frame_extended(@2169)
    append_frame(@2242,Object[#2823],Integer)
    append_frame(@2301,Object[#1452])
    same_locals_1_stack_item_frame(@2303,Object[#1452])
    chop_frame(@2319,1)
    full_frame(@2335,{Object[#2],Object[#2497]},{})

	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverInitiateHandshake(NetworkDispatcher.java:198) ~[NetworkDispatcher.class:git-CatServer-1.12.2-5fd7768]
	at net.minecraftforge.fml.common.network.handshake.FMLHandshakeServerState$1.accept(FMLHandshakeServerState.java:49) ~[FMLHandshakeServerState$1.class:git-CatServer-1.12.2-5fd7768]
	at net.minecraftforge.fml.common.network.handshake.HandshakeMessageHandler.userEventTriggered(HandshakeMessageHandler.java:65) ~[HandshakeMessageHandler.class:git-CatServer-1.12.2-5fd7768]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1352) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:920) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.insertIntoChannel(NetworkDispatcher.java:183) [NetworkDispatcher.class:git-CatServer-1.12.2-5fd7768]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:154) [NetworkDispatcher.class:git-CatServer-1.12.2-5fd7768]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:81) [FMLNetworkHandler.class:git-CatServer-1.12.2-5fd7768]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:185) [pc.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:70) [pc.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:187) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:934) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[13:12:20] [Server thread/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@742b71b1[id=8fd3a311-a3ce-30cc-8a8f-ea8fc390eb65,name=MinuteSphinx,properties={},legacy=false] (/192.168.50.1:2254): Took too long to log in`

Then client will return with
Connection Closed

Also tried with Classic Forge Server,it worked.

thanks for developing catserver!

**Comment by Luohuayu** [comment]
LibrarianLib mod is unsupport

**Comment by MinuteSphinx** [comment]
> 
> 
> LibrarianLib mod is unsupport

Thanks!
