### ISSUE TITLE
Maximum Potion IDs

### ISSUE THREAD

**Issue by Blacky25** [Luohuayu/CatServer#216]
Hello,

I'm using a lot of mods and I already use Just enough IDs mod to expand the ID Range. The Server is running when I use Forge Server only.

But with CatServer i ran out of ids.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2020-06-26 02:08:35 CEST
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 255
    at org.bukkit.potion.PotionEffectType.registerPotionEffectType(PotionEffectType.java:271)
    at catserver.server.BukkitInjector.registerPotions(BukkitInjector.java:104)
    at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:338)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:327)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
    at java.lang.Thread.run(Unknown Source)

**Comment by Luohuayu** [comment]
Fixed

**Comment by Serega007RU** [comment]
> Fixed

How was the problem solved? Has a commit been made that fixes this problem? Can I have a link to this commit?
