### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by ghost** [Luohuayu/CatServer#222]
With the newest Catserver Version  CatServer-de0a1c1  i have following error at startup:

[08:07:42] [Server thread/ERROR]: Error occurred while enabling CMI v8.7.0.3 (Is it up to date?)
java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap cannot be cast to java.util.HashMap
        at com.Zrips.CMI.Reflections.manageEnchantment(Reflections.java:491) ~[?:?]
        at com.Zrips.CMI.Modules.Enchants.EnchantManager.disableEnchantsOnLoad(EnchantManager.java:176) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1637) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-de0a1c1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-de0a1c1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-de0a1c1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436) [CraftServer.class:git-CatServer-1.12.2-de0a1c1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-de0a1c1]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by Luohuayu** [comment]
Fixed
