### ISSUE TITLE
CoreProtect 2020年2.28日版本及之后无法使用

### ISSUE THREAD

**Issue by Idle-Guest** [Luohuayu/CatServer#225]
我用2.28日 05e5dcd 之前的版本都能正常使用CoreProtect 虽然28日的更新是兼容CoreProtect
 05e5dcd 及之后的版本 把mod物品放入箱子 使用coi 不能正常查询
我使用的CoreProtect版本2.14.2   2.14.4 
使用报错
[12:03:18] [Thread-460/WARN] []: java.lang.NullPointerException
[12:03:18] [Thread-460/WARN] []: 	at net.coreprotect.database.Lookup.chest_transactions(Lookup.java:277)
[12:03:18] [Thread-460/WARN] []: 	at net.coreprotect.listener.PlayerListener$3BasicThread.run(PlayerListener.java:420)
[12:03:18] [Thread-460/WARN] []: 	at java.lang.Thread.run(Unknown Source)

**Comment by Luohuayu** [comment]
未复现该问题
