### ISSUE TITLE
Getting ProtocolLib error after it loaded.

### ISSUE THREAD

**Issue by LLjo** [Luohuayu/CatServer#232]
Getting this error on loading protocolLib (i tried many versions, unless i missed one that actually work):

[04:08:25] [Server thread/ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException
  	at com.comphenix.protocol.ProtocolConfig.getInjectionMethod(ProtocolConfig.java:462)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:208)
  	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:365)
  	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:342)
  	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327)
  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
  	at java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters: 
    com.comphenix.protocol.injector.PacketFilterManager@22da2539[
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@357760ff
      packetListeners=[]
      packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@49124d15
      playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@12218d70
      inputBufferedPackets=[]
      recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@61a181e0
      sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6f5f75b3
      hasClosed=false
      classLoader=org.bukkit.plugin.java.PluginClassLoader@589b2136
      reporter=com.comphenix.protocol.ProtocolLib$1@34fee7a8
      server=CraftServer{serverName=CatServer,serverVersion=git-CatServer-1.12.2-fb72736,minecraftVersion=1.12.2}
      library=ProtocolLib v4.6.0-SNAPSHOT-b472
      asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@47699c6e
      knowsServerPackets=true
      knowsClientPackets=true
      phaseLoginCount=0
      phasePlayingCount=0
      packetCreation=false
      nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6469e261
      pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4b975c42
      hasRecycleDistance=true
      minecraftVersion=(MC: 1.12.2)
      debug=false
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@22da2539[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@357760ff
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@49124d15
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@12218d70
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@61a181e0
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6f5f75b3
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@589b2136
        reporter=com.comphenix.protocol.ProtocolLib$1@34fee7a8
        server=CraftServer{serverName=CatServer,serverVersion=git-CatServer-1.12.2-fb72736,minecraftVersion=1.12.2}
        library=ProtocolLib v4.6.0-SNAPSHOT-b472
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@47699c6e
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6469e261
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4b975c42
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@24da0aee[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@357760ff
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@fd1c782
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@240046f3
      server=CraftServer{serverName=CatServer,serverVersion=git-CatServer-1.12.2-fb72736,minecraftVersion=1.12.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@55047b7d
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@589b2136
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@2011b823
    ]
  Version:
    ProtocolLib v4.6.0-SNAPSHOT-b472
  Java Version:
    1.8.0_241
  Server:
    git-CatServer-1.12.2-fb72736 (MC: 1.12.2)

**Comment by LLjo** [comment]
nvm newest version worked
