### ISSUE TITLE
EssentialsX plugin goes wrong

### ISSUE THREAD

**Issue by ghost** [Luohuayu/CatServer#234]
`[13:14:10] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[13:14:10] [Server thread/ERROR]: Error occurred while enabling Essentials v2.18.0.0 (Is it up to date?)
java.lang.IllegalArgumentException: The permission essentials.hat.prevent-type.pixelmon_temple_slab is already defined!
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:605) ~[SimplePluginManager.class:git-CatServer-1.12.2-27d41d1]
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:597) ~[SimplePluginManager.class:git-CatServer-1.12.2-27d41d1]
        at com.earth2me.essentials.commands.Commandhat.registerPermissionsIfNecessary(Commandhat.java:48) ~[?:?]
        at com.earth2me.essentials.Essentials.onEnable(Essentials.java:305) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-27d41d1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-27d41d1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-27d41d1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-27d41d1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-27d41d1]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]`

**Comment by LLjo** [comment]
try 2.0.1
that one works

**Comment by LLjo** [comment]
2.15.0.1 works too

**Comment by Heriptik** [comment]
EssentialsX 2.17.2 works perfectly

**Comment by LLjo** [comment]
yeah you are right, didnt know :D

**Comment by Luohuayu** [comment]
Fixed
