### ISSUE TITLE
可以添加GadgetsMenu支持嘛？

### ISSUE THREAD

**Issue by qq591692157** [Luohuayu/CatServer#235]
22:23:57] [Server thread/ERROR] [Minecraft]: Error occurred while enabling GadgetsMenu v4.5.27 (Is it up to date?)
java.lang.NoSuchFieldError: field_191309_d
	at com.yapzhenyie.GadgetsMenu.nms.v1_12_R1.pets.registry.NMSUtils.registerEntity(NMSUtils.java:209) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.nms.v1_12_R1.pets.registry.PetRegistry.registerPet(PetRegistry.java:113) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.nms.v1_12_R1.NMSManagerImpl.registerPets(NMSManagerImpl.java:88) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:254) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-27d41d1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-27d41d1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-27d41d1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-27d41d1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-27d41d1]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by Luohuayu** [comment]
Fixed
https://github.com/Luohuayu/CatServer/commit/11c12cd81c8b6065954f639c4e3300ed7586152b
