### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/world/World$3

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#239]
A fairly old error that has not yet been fixed. Is that your line? Or contact the author of the mod BOP?

```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/World$3
	at net.minecraft.world.World.func_190524_a(World.java:723)
	at net.minecraft.world.World.func_175685_c(World.java:653)
	at net.minecraft.world.World.func_175722_b(World.java:597)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:535)
	at net.minecraft.world.World.func_180501_a(World.java:514)
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:165)
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:194)
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:177)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1169)
	at net.minecraft.block.BlockLiquid.func_176365_e(BlockLiquid.java:295)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:319)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:658)
	at net.minecraft.world.World.func_180501_a(World.java:496)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:167)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:702)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:682)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:108)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:702)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:682)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:658)
	at net.minecraft.world.World.func_180501_a(World.java:496)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:167)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:702)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:682)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:658)
	at net.minecraft.world.World.func_180501_a(World.java:496)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:139)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:702)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:682)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:658)
	at net.minecraft.world.World.func_180501_a(World.java:496)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:143)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:702)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:682)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:658)
	at net.minecraft.world.World.func_180501_a(World.java:496)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:167)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:702)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:682)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:658)
	at net.minecraft.world.World.func_180501_a(World.java:496)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:167)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:702)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:682)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:658)
	at net.minecraft.world.World.func_180501_a(World.java:496)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:167)
	at net.minecraft.world.World.func_189507_a(World.java:3011)
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_180709_b(WorldGenLiquids.java:88)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:363)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:226)
	at net.minecraft.world.biome.BiomePlains.func_180624_a(BiomePlains.java:106)
	at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:565)
	at org.bukkit.craftbukkit.v1_12_R1.generator.NormalChunkGenerator.func_185931_b(NormalChunkGenerator.java:46)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1168)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:1070)
	at pregenerator.impl.processor.ChunkFile.populate(ChunkFile.java:91)
	at pregenerator.impl.processor.ChunkFile$ChunkFileEntry.process(ChunkFile.java:302)
	at pregenerator.impl.processor.ChunkProcessor.onServerTickEvent(ChunkProcessor.java:102)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1709_ChunkProcessor_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:268)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:820)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:628)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Luohuayu** [comment]
Do not set Xss flag of jvm

**Comment by dayd21git** [comment]
> Do not set Xss flag of jvm

i don't use this flag.
My flags: -Xincgc -server -Xmx8G -Xmn32M -Xms64m -Xminf0.1 -Xmaxf0.3

**Comment by Luohuayu** [comment]
> > Do not set Xss flag of jvm
> 
> i don't use this flag.
> My flags: -Xincgc -server -Xmx8G -Xmn32M -Xms64m -Xminf0.1 -Xmaxf0.3

Please set only Xmx and Xms
