### ISSUE TITLE
Could not pass event BlockBreakEvent to CoreProtect v2.12.0

### ISSUE THREAD

**Issue by kira-yamatoo** [Luohuayu/CatServer#259]
log:
[00:29:45] [Server thread/ERROR] [Minecraft]: Could not pass event BlockBreakEvent to CoreProtect v2.12.0
org.bukkit.event.EventException: null
	at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-237b0d4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-237b0d4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-237b0d4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-237b0d4]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1200) [CraftEventFactory.class:git-CatServer-1.12.2-237b0d4]
	at catserver.server.CatServerEventHandler.onBlockBreak(CatServerEventHandler.java:30) [CatServerEventHandler.class:git-CatServer-1.12.2-237b0d4]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_284_CatServerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-237b0d4]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-237b0d4]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-237b0d4]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:835) [ForgeHooks.class:git-CatServer-1.12.2-237b0d4]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:356) [or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:304) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1083) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at net.coreprotect.Functions.getSpawnerType(Functions.java:1248) ~[?:?]
	at net.coreprotect.consumer.Queue.queueBlockBreak(Queue.java:173) ~[?:?]
	at net.coreprotect.listener.BlockListener.onBlockBreak(BlockListener.java:452) ~[?:?]
	at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-237b0d4]
	... 23 more
[00:29:46] [Server thread/INFO] [ebwizardry]: Synchronising advancements for lilium
[00:29:54] [Server thread/INFO] [ebwizardry]: Synchronising advancements for liulaoshi
[00:29:55] [Server thread/INFO] [ebwizardry]: Synchronising advancements for lilium

plugin:coreprotect, version2.12.0.

**Comment by kira-yamatoo** [comment]
server version: CatServer-1.12.2-237b0d4

**Comment by kira-yamatoo** [comment]
得空的话可以帮看一下吗

**Comment by Heriptik** [comment]
Same error : https://paste.ubuntu.com/p/7QWQx7tSxm/

With coreprotect 2.14.4

**Comment by Luohuayu** [comment]
已修复
