### ISSUE TITLE
RandomPatches Timeout patch don't work

### ISSUE THREAD

**Issue by Michael-Hozza** [Luohuayu/CatServer#261]
Mod: https://www.curseforge.com/minecraft/mc-mods/randompatches
CatServer Version: 20.09.06
Issue: RandomPatches timeout patch doesnt work with CatServer. 

Log: 

`[09:52:34] [Server thread/ERROR] [randompatches]: Failed to transform class: net.minecraft.network.NetHandlerPlayServer
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(InsnList.java:347) ~[asm-debug-all-5.2.jar:5.2]
	at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.patchUpdate(NetHandlerPlayServerPatch.java:121) ~[NetHandlerPlayServerPatch.class:?]
	at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.apply(NetHandlerPlayServerPatch.java:26) ~[NetHandlerPlayServerPatch.class:?]
	at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) [ASMTransformerWrapper$TransformerWrapper.class:git-CatServer-1.12.2-a118ddc]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_262]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_262]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_262]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_262]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) [?:1.8.0_262]
	at java.lang.Class.getMethods(Class.java:1615) [?:1.8.0_262]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:84) [EventBus.class:git-CatServer-1.12.2-a118ddc]
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) [AutomaticEventSubscriber.class:git-CatServer-1.12.2-a118ddc]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611) [FMLModContainer.class:git-CatServer-1.12.2-a118ddc]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:git-CatServer-1.12.2-a118ddc]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:git-CatServer-1.12.2-a118ddc]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:git-CatServer-1.12.2-a118ddc]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595) [Loader.class:git-CatServer-1.12.2-a118ddc]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:git-CatServer-1.12.2-a118ddc]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335) [FMLCommonHandler.class:git-CatServer-1.12.2-a118ddc]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:166) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]`

**Comment by Luohuayu** [comment]
Not compatible, please set patchNetHandlerPlayServer of MOD configuration to false

**Comment by Michael-Hozza** [comment]
Is there any other way to increase the timeout timer? (Any config, or class to patch on my own?)

**Comment by TheRandomLabs** [comment]
This is fixed now.

**Comment by Luohuayu** [comment]
> 
> 
> This is fixed now.

Thanks

**Comment by bigenergy** [comment]
@TheRandomLabs https://github.com/TheRandomLabs/RandomPatches/issues/122
