### ISSUE TITLE
when server closed

### ISSUE THREAD

**Issue by 4Seasons11** [Luohuayu/CatServer#262]
[01:53:46] [JDA Shutdown Hook/WARN] []: Exception in thread "JDA Shutdown Hook" 
[01:53:46] [JDA Shutdown Hook/WARN] []: java.lang.NoClassDefFoundError: net/dv8tion/jda/internal/managers/AudioManagerImpl
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at net.dv8tion.jda.internal.JDAImpl.closeAudioConnections(JDAImpl.java:704)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at net.dv8tion.jda.internal.JDAImpl.shutdownInternals(JDAImpl.java:678)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at net.dv8tion.jda.internal.JDAImpl.shutdown(JDAImpl.java:670)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at java.lang.Thread.run(Unknown Source)
[01:53:46] [JDA Shutdown Hook/WARN] []: Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.internal.managers.AudioManagerImpl
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	... 4 more
[01:53:46] [JDA Shutdown Hook/WARN] []: Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.internal.managers.AudioManagerImpl
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at java.net.URLClassLoader.findClass(Unknown Source)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138)
[01:53:46] [JDA Shutdown Hook/WARN] []: 	... 7 more

**Comment by Luohuayu** [comment]
When Shutdown Hook, the plugin has been unloaded and PluginClassLoader has been closed, class cannot be loaded at this time.
Please take action when the plugin is unloading(onDisable method in plugin main class).
