### ISSUE TITLE
CannotConnectTomyServer

### ISSUE THREAD

**Issue by KubiRemPL** [Luohuayu/CatServer#27]
This issue is at 85% made by this script SPacketWorldBorder.java in the Pro version idn is the same name in async
Under is possible code that doing it 
this.centerX = border.getCenterX() * (border.world.provider instanceof WorldProviderHell ? 8 : 1);
this.centerZ = border.getCenterZ() * (border.world.provider instanceof WorldProviderHell ? 8 : 1);

Found this code in the Pro version.
But this happens on async 1.12.2 relese 
 
Can U check this
                                                                                                                     Best Regards KubiRemPL

**Comment by Luohuayu** [comment]
Can you explain your problem in more detail?

**Comment by KubiRemPL** [comment]
[17:47:39] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /127.0.0.1:54009
java.lang.NullPointerException: null
	at net.minecraft.network.play.server.SPacketWorldBorder.<init>(SPacketWorldBorder.java:34) ~[jz.class:?]
	at net.minecraft.server.management.PlayerList.updateTimeAndWeatherForPlayer(PlayerList.java:1617) ~[pl.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:271) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) ~[NetworkDispatcher.class:git-CatServerAsync-1.12.2-794beb8]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:git-CatServerAsync-1.12.2-794beb8]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:git-CatServerAsync-1.12.2-794beb8]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:235) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:187) [oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:937) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:473) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:779) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[17:47:39] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: KubiRem2005 lost connection: Disconnected
[17:47:39] [Server thread/INFO] [jecalculation]: Failed to load default records at C:\Users\rembi\Desktop\Testy2\config\JustEnoughCalculation\default.json.
[17:47:39] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: KubiRem2005 left the game


thats the message i am using otg

**Comment by Luohuayu** [comment]
Fixed

**Comment by KubiRemPL** [comment]
Thx so much

**Comment by KubiRemPL** [comment]
Does threded chunks will work with otg or mods

**Comment by Luohuayu** [comment]
Most of the mod things can't be asynchronous

**Comment by KubiRemPL** [comment]
Ok but just chunk generation??

**Comment by Luohuayu** [comment]
It works fine
