### ISSUE TITLE
Incompatibility plugins

### ISSUE THREAD

**Issue by JuanSlaterT** [Luohuayu/CatServer#282]
For some reason, one of my customers that bought a plugin from me is throwing this error

[Craft Scheduler Thread - 13/WARN] [hotdoctor.plugin.mysqlpapibridge.Main]: [MySQLPapiBridge] Plugin MySQLPapiBridge v2.0 generated an exception while executing task 36
java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.hikari.HikariDataSource
    at hotdoctor.plugin.mysqlpapibridge.MySQL.MySQL.<init>(Unknown Source) ~[?:?]
    at hotdoctor.plugin.mysqlpapibridge.Main.lambda$onEnable$0(Unknown Source) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-999edd9b]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-999edd9b]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_271]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_271]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

No idea why is throwing it, this only happens with CatServer, some way for fix it? it runs correctly with Bukkit, Spigot and Paperspigot servers.

**Comment by JuanSlaterT** [comment]
The plugin is made mainly as maven project so it needs to download some external libraries and apply it to the plugin, in this case I use HikariDB libraries for better perfomance between connections to my mysql.

**Comment by TheNullablePrototype** [comment]
Provide the code that is being executed.

**Comment by Luohuayu** [comment]
Please provide plugin download link or source code
