### ISSUE TITLE
EssentialsX 2.18.2 not working

### ISSUE THREAD

**Issue by bigenergy** [Luohuayu/CatServer#284]
```
[20:31:53] [Server thread/INFO] [com.earth2me.essentials.Essentials]: [Essentials] ServerListPingEvent: Spigot iterator API
[20:31:53] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Essentials v2.18.2.0 (Is it up to date?)
java.lang.IllegalArgumentException: The permission essentials.hat.prevent-type.atum_linen_silver is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:605) ~[SimplePluginManager.class:git-CatServer-1.12.2-affc3c3]
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:597) ~[SimplePluginManager.class:git-CatServer-1.12.2-affc3c3]
	at com.earth2me.essentials.perm.PermissionsDefaults.registerAllHatDefaults(PermissionsDefaults.java:47) ~[?:?]
	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:359) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-affc3c3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-affc3c3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-affc3c3]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-affc3c3]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-affc3c3]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:384) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

```
[20:32:37] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Big_Energy issued server command: /gc
[20:32:37] [Server thread/ERROR] [net.minecraft.network.NetHandlerPlayServer]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gc' in plugin Essentials v2.18.2.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-affc3c3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-affc3c3]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[CraftServer.class:git-CatServer-1.12.2-affc3c3]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1596) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:1439) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:839) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:569) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-affc3c3]
	... 15 more
```

**Comment by Luohuayu** [comment]
Did you enable `enableEssentialsNewVersionCompatible` in catserver.yml?

**Comment by bigenergy** [comment]
> Did you enable `enableEssentialsNewVersionCompatible` in catserver.yml?

Yes, enabled

**Comment by Luohuayu** [comment]
Fixed
