### ISSUE TITLE
Fawe Mod Support ?

### ISSUE THREAD

**Issue by ghost** [Luohuayu/CatServer#285]
[12:23:51] [ForkJoinPool-6-worker-2/WARN] [CatServer]: A Mod/Plugin try to async kill entity, it will be executed safely on the main server thread until return!
[12:23:51] [ForkJoinPool-6-worker-2/WARN] [CatServer]: Please check the stacktrace in debug.log and report the author.

And Server crashes.

I get this in latest Version and Server crash. I have installed Fawe Mod only.

**Comment by ghost** [comment]
[12:31:12] [ForkJoinPool-6-worker-4/WARN]: java.lang.ArrayIndexOutOfBoundsException: 19318
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at com.boydti.fawe.forge.v112.ForgeQueue_All.getPrevious(ForgeQueue_All.java:563)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at com.boydti.fawe.forge.v112.ForgeChunk_All.call(ForgeChunk_All.java:256)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at com.boydti.fawe.forge.v112.ForgeChunk_All.call(ForgeChunk_All.java:40)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.FutureTask.run(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]: java.lang.ArrayIndexOutOfBoundsException: 19316
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at com.boydti.fawe.forge.v112.ForgeQueue_All.getPrevious(ForgeQueue_All.java:563)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at com.boydti.fawe.forge.v112.ForgeChunk_All.call(ForgeChunk_All.java:256)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at com.boydti.fawe.forge.v112.ForgeChunk_All.call(ForgeChunk_All.java:40)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.FutureTask.run(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-4/WARN]:      at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[12:31:12] [ForkJoinPool-6-worker-2/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:13] [ForkJoinPool-6-worker-2/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:13] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:13] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:13] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:14] [ForkJoinPool-6-worker-2/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:14] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:14] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:15] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:15] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:15] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:15] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:16] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:16] [ForkJoinPool-6-worker-2/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:16] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:16] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:17] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:17] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:17] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:17] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:17] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:18] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:18] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:18] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:18] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:19] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:19] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:19] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:20] [ForkJoinPool-6-worker-2/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:22] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:22] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:22] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:23] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:23] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:23] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:23] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:24] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:24] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:24] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[12:31:24] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException

**Comment by Luohuayu** [comment]
Not supported. Asynchronous operations will cause the server to crash.

**Comment by ghost** [comment]
Hmm too bad but ok thanks.

**Comment by ghost** [comment]
There is no Async Alternative for Worldedit that can copy and paste large schematics with modblocks. Fawe or AWE Plugin dont know Modblocks. Fawe Forge is the only Alternative for a Hybrid Server.

**Comment by ghost** [comment]
Is it possible to move Catserver to Paper Engine ?
