### ISSUE TITLE
Arcade Mod

### ISSUE THREAD

**Issue by ghost** [Luohuayu/CatServer#286]
[12:58:45] [Server thread/WARN]: [Arcade] Task #19686 for Arcade v1.46d-Legacy generated an exception
java.lang.AbstractMethodError: Method ro/fr33styler/arcade/dR.getId()I is abstract
        at ro.fr33styler.arcade.dR.getId(SourceFile,LineNumberTable) ~[?:?]
        at ro.fr33styler.arcade.aE.a(SourceFile,LineNumberTable:47) ~[?:?]
        at ro.fr33styler.arcade.ak.a(SourceFile,LineNumberTable:133) ~[?:?]
        at ro.fr33styler.arcade.an.b(SourceFile,LineNumberTable:94) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-d35de0b]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-d35de0b]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

Can you fix it? The autor doenst give support for hybrid Clients

**Comment by Luohuayu** [comment]
The plugin is obfuscated? Obfuscation will break the remapper.
