### ISSUE TITLE
Pokegive error

### ISSUE THREAD

**Issue by fanzth** [Luohuayu/CatServer#288]
[08:09:19] [Server thread/WARN] [Minecraft]: Unexpected exception while parsing console command "pokegive aumgamer Riolu s"
org.bukkit.command.CommandException: Unhandled exception executing 'pokegive aumgamer Riolu s' in catserver.server.command.ModCustomCommand(pokegive)
	at catserver.server.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:65) ~[CraftSimpleCommandMap.class:git-CatServer-1.12.2-83d81a7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchVanillaCommand(CraftServer.java:724) ~[CraftServer.class:git-CatServer-1.12.2-83d81a7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:719) ~[CraftServer.class:git-CatServer-1.12.2-83d81a7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:696) [CraftServer.class:git-CatServer-1.12.2-83d81a7]
	at net.minecraft.server.dedicated.DedicatedServer$5.evaluate(DedicatedServer.java:812) [nz$5.class:?]
	at net.minecraft.server.dedicated.DedicatedServer$5.evaluate(DedicatedServer.java:800) [nz$5.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [Waitable.class:git-CatServer-1.12.2-83d81a7]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at net.minecraft.command.CommandBase.func_184882_a(CommandBase.java:91) ~[bi.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:59) ~[bj.class:?]
	at catserver.server.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:49) ~[CraftSimpleCommandMap.class:git-CatServer-1.12.2-83d81a7]
	... 11 more

**Comment by Luohuayu** [comment]
Unable to reproduce. Need more information.

**Comment by fanzth** [comment]
I have it only, What do u want more?

**Comment by fanzth** [comment]
It bugs only Pixelmon mod

**Comment by Heriptik** [comment]
I use CatServer and Pixelmon (reforged 8.1.2) and i don't have this problem, command works correctly

Check your sidemods / mods / plugins

**Comment by Luohuayu** [comment]
Pixelmon mod works fine. Please check other things.
