### ISSUE TITLE
Crop Growth is crashing the server.

### ISSUE THREAD

**Issue by Zilacon** [Luohuayu/CatServer#289]
Im using the Sky Factory 4 modpack and the server keeps crashing with this error whenever anything tries to grow:
```
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6]} as it does not exist in BlockStateContainer{block=minecraft:cactus, properties=[age]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
    at net.minecraft.block.BlockCrops.getAge(BlockCrops.java:57)
    at net.minecraft.block.BlockCrops.getMetaFromState(BlockCrops.java:259)
    at net.minecraft.block.BlockCrops.updateTick(BlockCrops.java:86)
    at net.minecraft.block.Block.randomTick(Block.java:508)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:605)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:331)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:896)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:776)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
    at java.lang.Thread.run(Thread.java:823)
```

Full crash report:
[message (20).txt](https://github.com/Luohuayu/CatServer/files/5683656/message.20.txt)

**Comment by Luohuayu** [comment]
Fixed

**Comment by Zilacon** [comment]
Thanks!
