### ISSUE TITLE
LuckPerms error flood

### ISSUE THREAD

**Issue by bigenergy** [Luohuayu/CatServer#290]
```
[08:35:30] [Server thread/WARN] [me.lucko.luckperms.bukkit.LPBukkitBootstrap]: [LuckPerms] An exception was thrown by me.lucko.luckperms.bukkit.context.BukkitPlayerCalculator whilst calculating the context of subject CraftPlayer{name=YuliaArno}
java.lang.ArrayIndexOutOfBoundsException: 17
	at me.lucko.luckperms.common.util.EnumNamer.name(EnumNamer.java:59) ~[LuckPerms-Bukkit-5.2.55.jar:?]
	at me.lucko.luckperms.bukkit.context.BukkitPlayerCalculator.calculate(BukkitPlayerCalculator.java:87) ~[LuckPerms-Bukkit-5.2.55.jar:?]
	at me.lucko.luckperms.bukkit.context.BukkitPlayerCalculator.calculate(BukkitPlayerCalculator.java:53) ~[LuckPerms-Bukkit-5.2.55.jar:?]
	at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:138) [LuckPerms-Bukkit-5.2.55.jar:?]
	at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54) [LuckPerms-Bukkit-5.2.55.jar:?]
	at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42) [LuckPerms-Bukkit-5.2.55.jar:?]
	at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64) [LuckPerms-Bukkit-5.2.55.jar:?]
	at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59) [LuckPerms-Bukkit-5.2.55.jar:?]
	at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.isPermissionSet(LuckPermsPermissible.java:145) [LuckPerms-Bukkit-5.2.55.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.isPermissionSet(CraftHumanEntity.java:130) [CraftHumanEntity.class:git-CatServer-1.12.2-d35de0b]
	at com.sk89q.wepif.DinnerPermsResolver.internalHasPermission(DinnerPermsResolver.java:149) [WorldEdit-6.1.9-SNAPSHOT-all.jar:?]
	at com.sk89q.wepif.DinnerPermsResolver.hasPermission(DinnerPermsResolver.java:76) [WorldEdit-6.1.9-SNAPSHOT-all.jar:?]
	at com.sk89q.wepif.DinnerPermsResolver.hasPermission(DinnerPermsResolver.java:97) [WorldEdit-6.1.9-SNAPSHOT-all.jar:?]
	at com.sk89q.wepif.PermissionsResolverManager.hasPermission(PermissionsResolverManager.java:173) [WorldEdit-6.1.9-SNAPSHOT-all.jar:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:510) [WorldGuard.jar:?]
	at com.sk89q.worldguard.bukkit.permission.AbstractPermissionModel.hasPluginPermission(AbstractPermissionModel.java:45) [WorldGuard.jar:?]
	at com.sk89q.worldguard.bukkit.permission.RegionPermissionModel.mayIgnoreRegionProtection(RegionPermissionModel.java:42) [WorldGuard.jar:?]
	at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.isWhitelisted(RegionProtectionListener.java:140) [WorldGuard.jar:?]
	at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onBreakBlock(RegionProtectionListener.java:225) [WorldGuard.jar:?]
	at catserver.server.executor.asm.generated.GeneratedEventExecutor125.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) [EventExecutor$2.class:git-CatServer-1.12.2-d35de0b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:git-CatServer-1.12.2-d35de0b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-d35de0b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-d35de0b]
	at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) [WorldGuard.jar:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onBlockBreak(EventAbstractionListener.java:124) [WorldGuard.jar:?]
	at catserver.server.executor.asm.generated.GeneratedEventExecutor171.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) [EventExecutor$2.class:git-CatServer-1.12.2-d35de0b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:git-CatServer-1.12.2-d35de0b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-d35de0b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-d35de0b]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1200) [CraftEventFactory.class:git-CatServer-1.12.2-d35de0b]
	at catserver.server.CatServerEventHandler.onBlockBreak(CatServerEventHandler.java:30) [CatServerEventHandler.class:git-CatServer-1.12.2-d35de0b]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_352_CatServerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-d35de0b]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-d35de0b]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-d35de0b]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:835) [ForgeHooks.class:git-CatServer-1.12.2-d35de0b]
	at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:356) [or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.blockRemoving(PlayerInteractionManager.java:304) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:1083) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:839) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```
flood to the console every second
LuckPerms-Bukkit-5.2.55
CatServer-d35de0b

**Comment by Luohuayu** [comment]
Not a CatServer problem. Check plugin configuration.
