### ISSUE TITLE
安装vanilla-immersion模组 启动服务端崩溃！

### ISSUE THREAD

**Issue by Kino0208** [Luohuayu/CatServer#295]
核心使用：CatServer-5068915-universal.jar
启动参数：java -Xms1024M -Xmx8192M -jar CatServer-5068915-universal.jar
插件：无
Mod：Forgelin-1.8.4.jar (模组前置)
           vanilla-immersion-1.12.2-2.0.3.3.jar （崩溃本体）

崩溃部分信息：
[crash-2020-12-30_02.42.08-server.txt](https://github.com/Luohuayu/CatServer/files/5751774/crash-2020-12-30_02.42.08-server.txt)
[latest.log](https://github.com/Luohuayu/CatServer/files/5751777/latest.log)

Time: 20-12-30 上午2:42
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Vanilla Immersion (vimmersion)
Caused by: java.lang.ExceptionInInitializerError
	at de.mineformers.vanillaimmersion.config.MutEntry$Category.freeze(builder.kt:182)
	at de.mineformers.vanillaimmersion.config.BuilderKt.config(builder.kt:277)
	at de.mineformers.vanillaimmersion.config.Configuration.<clinit>(Configuration.kt:30)
	at de.mineformers.vanillaimmersion.VanillaImmersion.preInit(VanillaImmersion.kt:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:636)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
	at java.lang.Thread.run(Unknown Source)
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: com.typesafe.config.impl.SimpleConfigOrigin.setComments(java.util.List)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(ReflectionHelper.java:303)
	at de.mineformers.vanillaimmersion.config.ConfigEntry$Category.<clinit>(template.kt:60)
	... 40 more
Caused by: java.lang.NoSuchMethodException: com.typesafe.config.impl.SimpleConfigOrigin.setComments(java.util.List)
	at java.lang.Class.getDeclaredMethod(Unknown Source)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(ReflectionHelper.java:297)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by Luohuayu** [comment]
已修复
