### ISSUE TITLE
Another "growth" crash.

### ISSUE THREAD

**Issue by Zilacon** [Luohuayu/CatServer#296]
After you fixed the growth issues for crops, it seems theres one for animals as well.

```
[09:56:41] [Spigot Watchdog Thread/ERROR]: Current Thread: Server thread
[09:56:41] [Spigot Watchdog Thread/ERROR]: 	PID: 33 | Suspended: false | Native: false | State: RUNNABLE
[09:56:41] [Spigot Watchdog Thread/ERROR]: 	Stack:
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.Entity.func_184208_bv(Entity.java:3691)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.Entity.func_184223_x(Entity.java:3701)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.world.World.func_184144_a(World.java:1621)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.Entity.func_70091_d(Entity.java:893)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:2283)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2724)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:623)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:207)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.passive.EntityAnimal.func_70636_d(EntityAnimal.java:46)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2506)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:332)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.Entity.func_70098_U(Entity.java:2299)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2828)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.world.World.func_72866_a(World.java:2298)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.world.World.func_72870_g(World.java:2257)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.world.World.func_72866_a(World.java:2364)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.world.World.func_72870_g(World.java:2257)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:773)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.world.World.func_72939_s(World.java:1990)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:909)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
[09:56:41] [Spigot Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:823)
```

**Comment by Luohuayu** [comment]
Not "growth" crash. It is watchdog caused by the server main thread lagg for more than one minute. I cannot get more useful information from the log.

**Comment by Zilacon** [comment]
@Luohuayu Here is another one from a different pack:
```
[16:19:22] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:903) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:776) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]
Caused by: java.lang.IllegalAccessError: Class growthcraft/hops/common/block/BlockHops illegally accessing "protected" member of class net/minecraft/block/BlockCrops
	at growthcraft.hops.common.block.BlockHops.getGrowthRate(BlockHops.java:254) ~[BlockHops.class:?]
	at growthcraft.hops.common.block.BlockHops.getGrowthRateLoop(BlockHops.java:200) ~[BlockHops.class:?]
	at growthcraft.hops.common.block.BlockHops.grow(BlockHops.java:236) ~[BlockHops.class:?]
	at growthcraft.hops.common.block.BlockHops.updateTick(BlockHops.java:162) ~[BlockHops.class:?]
	at net.minecraft.block.Block.randomTick(Block.java:508) ~[aow.class:?]
	at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:605) ~[oo.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:331) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:896) ~[MinecraftServer.class:?]
	... 4 more
```
Crash Report: 
[crash-2021-01-04_16.19.22-server.txt](https://github.com/Luohuayu/CatServer/files/5767373/crash-2021-01-04_16.19.22-server.txt)
