### ISSUE TITLE
所以这个是啥报错

### ISSUE THREAD

**Issue by beamwu** [Luohuayu/CatServer#298]
[22:53:21] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[22:53:22] [Server thread/ERROR]: Parsing error loading recipe jaffa:maplecandiedbacon
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 19 column 4 path $.ingredients[3].
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:494) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:720) ~[CraftingHelper.class:git-CatServer-1.12.2-2a9163f]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:git-CatServer-1.12.2-2a9163f]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:git-CatServer-1.12.2-2a9163f]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_251]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:git-CatServer-1.12.2-2a9163f]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:git-CatServer-1.12.2-2a9163f]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:git-CatServer-1.12.2-2a9163f]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:341) [FMLCommonHandler.class:git-CatServer-1.12.2-2a9163f]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:275) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:591) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 19 column 4 path $.ingredients[3].
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[JsonReader.class:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:508) ~[JsonReader.class:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[JsonReader.class:?]
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[TypeAdapters$29.class:?]
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731) ~[TypeAdapters$29.class:?]
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[TypeAdapters$29.class:?]
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[TypeAdapters$35$1.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        ... 12 more
[22:53:22] [Server thread/INFO]: Ignored smelting recipe with conflicting input: 1xic2.dust@8 = 1xitem.ingotIron@0
[22:53:22] [Server thread/INFO]: Ignored smelting recipe with conflicting input: 1xic2.dust@7 = 1xitem.ingotGold@0

**Comment by EnterFor** [comment]
删除 Just Another Fun Food Addon 模组
我猜的，只能帮你到这了
