### ISSUE TITLE
Failed to re-register a Channel to the new Selector.

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#299]
```
[20:50:31] [Netty Server IO #0/WARN]: Failed to re-register a Channel to the new Selector.
java.lang.ClassCastException: io.netty.channel.nio.SelectedSelectionKeySetSelector cannot be cast to java.nio.channels.spi.AbstractSelector
        at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:219) ~[?:1.8.0_275]
        at io.netty.channel.nio.NioEventLoop.rebuildSelector0(NioEventLoop.java:347) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.rebuildSelector(NioEventLoop.java:318) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:769) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388) [minecraft_server.1.12.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[20:50:31] [Netty Server IO #0/INFO]: Migrated 0 channel(s) to the new Selector.
```
After the server starts, it gets the offline status. There is an error in the logs. Does this apply to you or not?

**Comment by Luohuayu** [comment]
Are you using the latest release?

**Comment by dayd21git** [comment]
Yes!

**Comment by dayd21git** [comment]
Any ideas?

**Comment by Luohuayu** [comment]
Can you upload the full log?

**Comment by Luohuayu** [comment]
It seems you are running `minecraft_server.1.12.2.jar` instead of CatServer

**Comment by dayd21git** [comment]
log1: https://drive.google.com/file/d/1HXlJ6F3ZzbsiynJVIemB1zzWPsmliGsH/view?usp=sharing
log2: https://drive.google.com/file/d/1bVsApYzAq1VGAYa66wRW998EOhGY3MRU/view?usp=sharing
start.sh: https://drive.google.com/file/d/14bb6MwoLNk8hMxsir2guaXghkGI46Wod/view?usp=sharing

**Comment by Luohuayu** [comment]
Try not to use javaagent, use `java -jar server.jar` to start

**Comment by dayd21git** [comment]
Hey! `/home/jdk8u275/bin/java`

**Comment by dayd21git** [comment]
it's line `# java -javaagent:LaunchServer.jar -jar LaunchServer.jar;` not used!

**Comment by Luohuayu** [comment]
Try to use the latest release now, the problem should be resolved.

**Comment by dayd21git** [comment]
Rly? Ok!
