### ISSUE TITLE
ConcurrentModificationException导致崩服

### ISSUE THREAD

**Issue by CraftDream** [Luohuayu/CatServer#310]
crash如下
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at net.minecraft.server.management.PlayerChunkMap$3.computeNext(PlayerChunkMap.java:78)
	at net.minecraft.server.management.PlayerChunkMap$3.computeNext(PlayerChunkMap.java:71)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:436)
	at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:534)
	at net.minecraftforge.common.ForgeChunkManager.getPersistentChunksIterableFor(ForgeChunkManager.java:150)
	at net.minecraft.world.World.getPersistentChunkIterable(World.java:4287)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:517)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:331)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:897)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:773)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Luohuayu** [comment]
请提供崩溃时的debug.log和crash文件

**Comment by CraftDream** [comment]
[crash-2021-02-16_17.37.59-server.txt](https://github.com/Luohuayu/CatServer/files/5989085/crash-2021-02-16_17.37.59-server.txt)
[debug-2.log](https://github.com/Luohuayu/CatServer/files/5989088/debug-2.log)

**Comment by Luohuayu** [comment]
反馈PaoDan插件作者修复或者删除该插件, 异步传送玩家造成崩溃

**Comment by CraftDream** [comment]
明白了，thx
