### ISSUE TITLE
Random ArrayIndexOutOfBoundsException crush on async

### ISSUE THREAD

**Issue by TheDarkDnKTv** [Luohuayu/CatServer#32]
It randomly happened when i tryed to join server.

```
java.lang.ArrayIndexOutOfBoundsException: -1934515016
	at java.util.Vector.elementData(Unknown Source)
	at java.util.Vector.get(Unknown Source)
	at net.minecraft.world.World.func_72939_s(World.java:2131)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:747)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:909)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633)
	at java.lang.Thread.run(Unknown Source)
```

More info:
[crash-2019-11-26_06.50.20-server.txt](https://github.com/Luohuayu/CatServer/files/3889977/crash-2019-11-26_06.50.20-server.txt)

**Comment by Luohuayu** [comment]
Unable to clarify the problem, please replace the stable version if it keeps happening

**Comment by TheDarkDnKTv** [comment]
> Unable to clarify the problem, please replace the stable version if it keeps happening

Looks like it is happened once per last 36 hours... We can see "Unknown Source", maybe some plugin or mod runs Vector class and do some errors....
