### ISSUE TITLE
世界加载事件出现数组越界

### ISSUE THREAD

**Issue by Ling-G** [Luohuayu/CatServer#328]
plugins:Dynmap-3.1-spigot
mod:GalacticraftCore-1.12.2-4.0.2.280
server:CatServer-92b87c7-universal
卫星地图插件和星系MOD同时使用后，服务器启动后玩家进入其他星球服务器载入世界时候报错
之后在星系地图内的所有事件都会报错，循环刷屏至服务器崩溃（可能需要十几小时）

```
[15:55:17] [Server thread/INFO]: Huan_Meng_Jing[/127.0.0.1:59711] logged in with entity id 287 at ([world]418.56574314785416, 1206.7999999445863, -207.99565899417868)
[15:55:17] [Server thread/INFO]: -------- World Settings For [DIM-30] --------
[15:55:17] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:55:17] [Server thread/INFO]: View Distance: 10
[15:55:17] [Server thread/INFO]: Arrow Despawn Rate: 1200
[15:55:17] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[15:55:17] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[15:55:17] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[15:55:17] [Server thread/INFO]: Item Merge Radius: 2.5
[15:55:17] [Server thread/INFO]: Item Despawn Rate: 6000
[15:55:17] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[15:55:17] [Server thread/INFO]: Experience Merge Radius: 3.0
[15:55:17] [Server thread/INFO]: Mob Spawn Range: 4
[15:55:17] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[15:55:17] [Server thread/INFO]: Cactus Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: Cane Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: Melon Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: Sapling Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: Wheat Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: Vine Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[15:55:17] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[15:55:17] [Server thread/INFO]: Random Lighting Updates: false
[15:55:17] [Server thread/INFO]: Structure Info Saving: true
[15:55:17] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:55:17] [Server thread/INFO]: Max TNT Explosions: 100
[15:55:17] [Server thread/INFO]: Loading dimension -30 (DIM-30) (net.minecraft.server.dedicated.DedicatedServer@e39fc2d)
[15:55:18] [Server thread/ERROR]: Could not pass event WorldLoadEvent to dynmap v3.2-SNAPSHOT-Dev
org.bukkit.event.EventException: null
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:314) [DimensionManager.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:986) [MinecraftServer.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getWorldForDimensionServer(WorldUtil.java:324) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getProviderForDimensionServer(WorldUtil.java:336) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getPossibleDimensionsForSpaceshipTier(WorldUtil.java:198) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getArrayOfPossibleDimensions(WorldUtil.java:366) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.sendPlanetList(GCPlayerHandler.java:1199) [GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1396) [GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:340) [EventHandlerGC.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_340_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:565) [ForgeHooks.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2425) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:248) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:467) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:249) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:187) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:935) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:770) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
        at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:41) ~[?:?]
        at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:30) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.getWorld(DynmapPlugin.java:156) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.access$300(DynmapPlugin.java:110) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin$19.onWorldLoad(DynmapPlugin.java:1538) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-92b87c7]
        ... 28 more
[15:55:18] [Server thread/INFO]: -------- World Settings For [DIM-29] --------
[15:55:18] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:55:18] [Server thread/INFO]: View Distance: 10
[15:55:18] [Server thread/INFO]: Arrow Despawn Rate: 1200
[15:55:18] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[15:55:18] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[15:55:18] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[15:55:18] [Server thread/INFO]: Item Merge Radius: 2.5
[15:55:18] [Server thread/INFO]: Item Despawn Rate: 6000
[15:55:18] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[15:55:18] [Server thread/INFO]: Experience Merge Radius: 3.0
[15:55:18] [Server thread/INFO]: Mob Spawn Range: 4
[15:55:18] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[15:55:18] [Server thread/INFO]: Cactus Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Cane Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Melon Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Sapling Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Wheat Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Vine Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[15:55:18] [Server thread/INFO]: Random Lighting Updates: false
[15:55:18] [Server thread/INFO]: Structure Info Saving: true
[15:55:18] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:55:18] [Server thread/INFO]: Max TNT Explosions: 100
[15:55:18] [Server thread/INFO]: Loading dimension -29 (DIM-29) (net.minecraft.server.dedicated.DedicatedServer@e39fc2d)
[15:55:18] [Server thread/ERROR]: Could not pass event WorldLoadEvent to dynmap v3.2-SNAPSHOT-Dev
org.bukkit.event.EventException: null
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:314) [DimensionManager.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:986) [MinecraftServer.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getWorldForDimensionServer(WorldUtil.java:324) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getProviderForDimensionServer(WorldUtil.java:336) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getPossibleDimensionsForSpaceshipTier(WorldUtil.java:198) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getArrayOfPossibleDimensions(WorldUtil.java:366) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.sendPlanetList(GCPlayerHandler.java:1199) [GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1396) [GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:340) [EventHandlerGC.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_340_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:565) [ForgeHooks.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2425) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:248) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:467) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:249) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:187) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:935) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:770) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
        at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:41) ~[?:?]
        at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:30) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.getWorld(DynmapPlugin.java:156) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.access$300(DynmapPlugin.java:110) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin$19.onWorldLoad(DynmapPlugin.java:1538) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-92b87c7]
        ... 28 more
[15:55:18] [Server thread/INFO]: -------- World Settings For [DIM-31] --------
[15:55:18] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:55:18] [Server thread/INFO]: View Distance: 10
[15:55:18] [Server thread/INFO]: Arrow Despawn Rate: 1200
[15:55:18] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[15:55:18] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[15:55:18] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[15:55:18] [Server thread/INFO]: Item Merge Radius: 2.5
[15:55:18] [Server thread/INFO]: Item Despawn Rate: 6000
[15:55:18] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[15:55:18] [Server thread/INFO]: Experience Merge Radius: 3.0
[15:55:18] [Server thread/INFO]: Mob Spawn Range: 4
[15:55:18] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[15:55:18] [Server thread/INFO]: Cactus Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Cane Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Melon Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Sapling Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Wheat Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Vine Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[15:55:18] [Server thread/INFO]: Random Lighting Updates: false
[15:55:18] [Server thread/INFO]: Structure Info Saving: true
[15:55:18] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:55:18] [Server thread/INFO]: Max TNT Explosions: 100
[15:55:18] [Server thread/INFO]: Loading dimension -31 (DIM-31) (net.minecraft.server.dedicated.DedicatedServer@e39fc2d)
[15:55:18] [Server thread/ERROR]: Could not pass event WorldLoadEvent to dynmap v3.2-SNAPSHOT-Dev
org.bukkit.event.EventException: null
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:314) [DimensionManager.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:986) [MinecraftServer.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getWorldForDimensionServer(WorldUtil.java:324) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getProviderForDimensionServer(WorldUtil.java:336) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getPossibleDimensionsForSpaceshipTier(WorldUtil.java:198) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getArrayOfPossibleDimensions(WorldUtil.java:366) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.sendPlanetList(GCPlayerHandler.java:1199) [GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1396) [GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:340) [EventHandlerGC.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_340_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:565) [ForgeHooks.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2425) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:248) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:467) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:249) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:187) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:935) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:770) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
        at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:41) ~[?:?]
        at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:30) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.getWorld(DynmapPlugin.java:156) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.access$300(DynmapPlugin.java:110) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin$19.onWorldLoad(DynmapPlugin.java:1538) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-92b87c7]
        ... 28 more
[15:55:18] [Server thread/INFO]: -------- World Settings For [DIM-28] --------
[15:55:18] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:55:18] [Server thread/INFO]: View Distance: 10
[15:55:18] [Server thread/INFO]: Arrow Despawn Rate: 1200
[15:55:18] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[15:55:18] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[15:55:18] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[15:55:18] [Server thread/INFO]: Item Merge Radius: 2.5
[15:55:18] [Server thread/INFO]: Item Despawn Rate: 6000
[15:55:18] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[15:55:18] [Server thread/INFO]: Experience Merge Radius: 3.0
[15:55:18] [Server thread/INFO]: Mob Spawn Range: 4
[15:55:18] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[15:55:18] [Server thread/INFO]: Cactus Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Cane Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Melon Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Sapling Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Wheat Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Vine Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[15:55:18] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[15:55:18] [Server thread/INFO]: Random Lighting Updates: false
[15:55:18] [Server thread/INFO]: Structure Info Saving: true
[15:55:18] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:55:18] [Server thread/INFO]: Max TNT Explosions: 100
[15:55:18] [Server thread/INFO]: Loading dimension -28 (DIM-28) (net.minecraft.server.dedicated.DedicatedServer@e39fc2d)
[15:55:18] [Server thread/ERROR]: Could not pass event WorldLoadEvent to dynmap v3.2-SNAPSHOT-Dev
org.bukkit.event.EventException: null
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:314) [DimensionManager.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:986) [MinecraftServer.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getWorldForDimensionServer(WorldUtil.java:324) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getProviderForDimensionServer(WorldUtil.java:336) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getPossibleDimensionsForSpaceshipTier(WorldUtil.java:198) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.util.WorldUtil.getArrayOfPossibleDimensions(WorldUtil.java:366) [WorldUtil.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.sendPlanetList(GCPlayerHandler.java:1199) [GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1396) [GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:340) [EventHandlerGC.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_340_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:565) [ForgeHooks.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2425) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:248) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:467) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:249) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:187) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:935) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:770) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 7
        at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:41) ~[?:?]
        at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:30) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.getWorld(DynmapPlugin.java:156) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.access$300(DynmapPlugin.java:110) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin$19.onWorldLoad(DynmapPlugin.java:1538) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-92b87c7]
        ... 28 more
```

**Comment by Luohuayu** [comment]
dynmap插件版对mod世界兼容较差, 建议使用forge mod版
