### ISSUE TITLE
龙之研究崩溃

### ISSUE THREAD

**Issue by fenghuax112** [Luohuayu/CatServer#329]
at com.brandon3055.draconicevolution.handlers.CustomArmorHandler.onPlayerAttacked(CustomArmorHandler.java:102) ~[CustomArmorHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_592_CustomArmorHandler_onPlayerAttacked_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-83d81a7]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) ~[EventBus.class:git-CatServer-1.12.2-83d81a7]
        at net.minecraftforge.common.ForgeHooks.onPlayerAttack(ForgeHooks.java:575) ~[ForgeHooks.class:git-CatServer-1.12.2-83d81a7]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1040) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:816) ~[oq.class:?]
后台一直在刷然后就崩溃了 没有日志

**Comment by Luohuayu** [comment]
请提供完整日志
