### ISSUE TITLE
FAWE

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#330]
[22:26:31] [Server thread/WARN] []: java.lang.NoSuchMethodError: net.minecraft.world.gen.ChunkProviderServer.getChunkAt(IILjava/lang/Runnable;Z)Lnet/minecraft/world/chunk/Chunk;
[22:26:31] [Server thread/WARN] []: 	at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.loadChunk(BukkitQueue_1_12.java:182)
[22:26:31] [Server thread/WARN] []: 	at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.loadChunk(BukkitQueue_1_12.java:51)
[22:26:31] [Server thread/WARN] []: 	at com.boydti.fawe.example.MappedFaweQueue$3.run(MappedFaweQueue.java:431)
[22:26:31] [Server thread/WARN] []: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:124)
[22:26:31] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[22:26:31] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421)
[22:26:31] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:828)
[22:26:31] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[22:26:31] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:773)
[22:26:31] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
[22:26:31] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)

FastAsyncWorldEdit-bukkit-21.03.26-b67f782-1287-22.3.10.jar
https://ci.athion.net/job/FastAsyncWorldEdit/

**Comment by dayd21git** [comment]
Are there possible solutions to the problem?

**Comment by Luohuayu** [comment]
Not compatible with FAWE
