### ISSUE TITLE
java11

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#338]
Start server and crash
```
Current Java version (11.0.11) is not supported, please replace to Java8
Trying to use Java11 compatibility mode to start (even if the server can start, some mods and plugins may not work, please use Java8 if an error occurs)
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider scala.tools.nsc.interpreter.IMain$Factory not found
A problem occurred running the Server launcher.
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at catserver.server.CatServerLaunch.main(CatServerLaunch.java:13)
        at pro.gravit.launcher.server.ServerWrapper.run(ServerWrapper.java:209)
        at pro.gravit.launcher.server.ServerWrapper.main(ServerWrapper.java:70)
Caused by: java.lang.NoClassDefFoundError: org/jline/terminal/Terminal
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.base/java.lang.Class.getDeclaredMethods(Unknown Source)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.createBuilder(PluginBuilder.java:147)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:119)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:242)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:618)
        at net.minecraft.launchwrapper.LogWrapper.configureLogging(LogWrapper.java:14)
        at net.minecraft.launchwrapper.LogWrapper.log(LogWrapper.java:28)
        at catserver.server.launch.Java11Launch.launch(Java11Launch.java:75)
        at catserver.server.launch.Java11Launch.main(Java11Launch.java:22)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: org.jline.terminal.Terminal
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 36 more

```

**Comment by dayd21git** [comment]
Attempt to update files
```2021.06.30 12:45:17 [INFO] Start Minecraft Server
Current Java version (11.0.11) is not supported, please replace to Java8
Trying to use Java11 compatibility mode to start (even if the server can start, some mods and plugins may not work, please use Java8 if an error occurs)
Missing libraries file, downloading.. (Add -Dcatserver.skipCheckLibraries=true to the jvm flag to skip it)
java.net.ConnectException: Connection timed out (Connection timed out)
Downloading jline-3.5.1.jar Size: -1 B
File download failed(HTTP Status: java.net.SocketTimeoutException: connect timed out), URL: http://sv.catserver.moe:8001/dl/jline-3.5.1.jar
Downloading jline-3.5.1.jar Size: -1 B
File download failed(HTTP Status: java.net.SocketTimeoutException: connect timed out), URL: http://sv2.catserver.moe:8001/dl/jline-3.5.1.jar
Downloading jline-3.5.1.jar Size: 600.18555 KB
The libraries file download completed, if an error occurs only need re-run the server
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider scala.tools.nsc.interpreter.IMain$Factory not found
A problem occurred running the Server launcher.
```

**Comment by Luohuayu** [comment]
Download and unzip: https://github.com/Luohuayu/CatServerRes/blob/master/dl/libraries.zip
