### ISSUE TITLE
server start, java11

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#339]
```Time: 7/2/21, 2:52 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: enderioconduitsappliedenergistics Failed to load new mod instance.
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:603)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:168)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: crazypants.enderio.conduits.conduit.TileConduitBundle
	at com.enderio.core.common.transform.EnderCorePlugin$MixinData.initialize(EnderCorePlugin.java:54)
	at com.enderio.core.common.transform.EnderCorePlugin.lambda$loadMixinSources$1(EnderCorePlugin.java:110)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.enderio.core.common.transform.EnderCorePlugin.loadMixinSources(EnderCorePlugin.java:110)
	at com.enderio.core.common.transform.EnderCorePlugin.loadMixinSources(EnderCorePlugin.java:103)
	at com.enderio.core.common.transform.EnderCorePlugin.loadMixinSources(EnderCorePlugin.java:99)
	at com.enderio.core.common.mixin.SimpleMixinLoader.loadMixinSources(SimpleMixinLoader.java:8)
	at crazypants.enderio.conduit.me.EnderIOConduitsAppliedEnergistics.<init>(EnderIOConduitsAppliedEnergistics.java:56)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:191)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:598)
	... 30 more
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.conduits.conduit.TileConduitBundle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at com.enderio.core.common.transform.EnderCorePlugin$MixinData.initialize(EnderCorePlugin.java:51)
	... 44 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.enderio.core.common.transform.SimpleMixinPatcher@7a4138fe from coremod EnderCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:173)
	... 49 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
	at net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:73)
	at com.enderio.core.common.transform.NoClassloadClassWriter.getClassBytes(NoClassloadClassWriter.java:167)
	at com.enderio.core.common.transform.NoClassloadClassWriter.getClassInfo(NoClassloadClassWriter.java:139)
	at com.enderio.core.common.transform.NoClassloadClassWriter.getCommonSuperClass(NoClassloadClassWriter.java:72)
	at org.objectweb.asm.ClassWriter.getMergedType(ClassWriter.java:1698)
	at org.objectweb.asm.Frame.merge(Frame.java:1530)
	at org.objectweb.asm.Frame.merge(Frame.java:1429)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1516)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:835)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:412)
	at com.enderio.core.common.transform.SimpleMixinPatcher.transform(SimpleMixinPatcher.java:152)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 51 more```

**Comment by dayd21git** [comment]
It's not a good idea to change the server1.12 in java11

**Comment by Luohuayu** [comment]
Experimental feature, please use Java8
