### ISSUE TITLE
与FakePlayer同时运行后崩溃

### ISSUE THREAD

**Issue by Yecgaa1** [Luohuayu/CatServer#343]
该崩溃发生在我创建假人后，真玩家退出服务器后又重新进入服务器时服务端崩溃
关键代码为：
```
[20:22:09] [错误]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@5172e0ff:
java.lang.NullPointerException: Player can't be found for 1:15468a55d6633077a691aed0be0ffacf:io.github.portlek.fakeplayer.nms.v1_12_R1.NPC
	at com.feed_the_beast.ftblib.lib.data.Universe.getPlayer(Universe.java:822) ~[Universe.class:?]
	at com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesServerEventHandler.onServerTick(FTBUtilitiesServerEventHandler.java:163) ~[FTBUtilitiesServerEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_168_FTBUtilitiesServerEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-5744880]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-5744880]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:268) [FMLCommonHandler.class:git-CatServer-1.12.2-5744880]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:816) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[20:22:09] [错误]: Index: 1 Listeners:
[20:22:09] [错误]: 0: NORMAL
[20:22:09] [错误]: 1: ASM: class com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesServerEventHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 2: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [ERROR]: 3: ASM: class me.desht.pneumaticcraft.common.TemporaryBlockManager tickAll(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 4: ASM: net.minecraftforge.common.ForgeInternalHandler@63e28ac0 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 5: ASM: p455w0rdslib.handlers.ProcessHandler@1d1d05d9 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 6: ASM: oreexcavation.handlers.EventHandler@2ff6614b onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 7: ASM: me.desht.pneumaticcraft.common.event.TickHandlerPneumaticCraft@309ecb99 onServerTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 8: ASM: cofh.thermaldynamics.util.TickHandler@5a44fe4c onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 9: ASM: com.mmyzd.nmsot.NoMobSpawningOnTrees@311b832a onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 10: ASM: me.desht.pneumaticcraft.common.event.HackTickHandler@4705cafd onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 11: ASM: me.desht.pneumaticcraft.common.semiblock.SemiBlockManager@18d0d028 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 12: ASM: codechicken.multipart.handler.MultipartEventHandler$@5a8bf8c3 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 13: ASM: mrtjp.projectred.relocation.RelocationEventHandler$@7a0f58b8 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: 14: ASM: appeng.hooks.TickHandler@63ecf4f5 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[20:22:09] [错误]: 15: LOWEST
[20:22:09] [错误]: 16: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:22:09] [错误]: Encountered an unexpected exception
java.lang.NullPointerException: Player can't be found for 1:15468a55d6633077a691aed0be0ffacf:io.github.portlek.fakeplayer.nms.v1_12_R1.NPC
	at com.feed_the_beast.ftblib.lib.data.Universe.getPlayer(Universe.java:822) ~[Universe.class:?]
	at com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesServerEventHandler.onServerTick(FTBUtilitiesServerEventHandler.java:163) ~[FTBUtilitiesServerEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_168_FTBUtilitiesServerEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-5744880]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) ~[EventBus.class:git-CatServer-1.12.2-5744880]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:268) ~[FMLCommonHandler.class:git-CatServer-1.12.2-5744880]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:816) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```
插件名：FakePlayer 2.1.1（2.1.0也是一样的问题）
完整错误报告如下
[crash-2021-07-25_20.22.09-server.txt](https://github.com/Luohuayu/CatServer/files/6873853/crash-2021-07-25_20.22.09-server.txt)

**Comment by Yecgaa1** [comment]
我意识到这似乎与服务端catserver无关，与ftb有关，非常抱歉。
