### ISSUE TITLE
Mythicmobs projectiles not working

### ISSUE THREAD

**Issue by LLjo** [Luohuayu/CatServer#359]
MythicMobs  projectile skills doesn't work. I have no idea if it's an easy fix but the mod is heavy dependent on it. 

[04:40:28] [Server thread/ERROR]: [MythicMobs] [SCHEDULER] Exception thrown whilst executing task
[04:40:28] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.block.Block.isPassable()Z
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.util.BlockUtil.isPathable(BlockUtil.java:41)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.mechanics.ProjectileMechanic$ProjectileMechanicTracker.projectileTick(ProjectileMechanic.java:227)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.projectiles.Projectile$ProjectileTracker.run(Projectile.java:406)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.projectiles.Projectile$ProjectileTracker.lambda$start$12(Projectile.java:383)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.utils.Delegates$RunnableToFunction.apply(Delegates.java:189)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.utils.promise.LuminePromise$ApplyRunnable.run(LuminePromise.java:684)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.utils.promise.LuminePromise.executeSync(LuminePromise.java:133)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.utils.promise.LuminePromise.lambda$thenApplySync$1(LuminePromise.java:364)
[04:40:28] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
[04:40:28] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
[04:40:28] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.utils.promise.LuminePromise.thenApplySync(LuminePromise.java:360)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.utils.promise.Promise.thenRunSync(Promise.java:1019)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.projectiles.Projectile$ProjectileTracker.start(Projectile.java:346)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.mechanics.ProjectileMechanic$ProjectileMechanicTracker.<init>(ProjectileMechanic.java:88)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.mechanics.ProjectileMechanic.castAtLocation(ProjectileMechanic.java:63)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.mechanics.ProjectileMechanic.castAtEntity(ProjectileMechanic.java:73)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.lambda$executeTargetedEntitySkill$5(SkillMechanic.java:462)
[04:40:28] [Server thread/WARN]:        at java.lang.Iterable.forEach(Unknown Source)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.executeTargetedEntitySkill(SkillMechanic.java:458)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.executeSkills(SkillMechanic.java:411)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.execute(SkillMechanic.java:326)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.Skill.execute(Skill.java:270)
[04:40:28] [Server thread/WARN]:        at io.lumine.xikage.mythicmobs.skills.AbstractSkill$DelayedSkill.run(AbstractSkill.java:497)
[04:40:28] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[04:40:28] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421)
[04:40:28] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:882)
[04:40:28] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474)
[04:40:28] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826)
[04:40:28] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685)
[04:40:28] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Luohuayu** [comment]
The plugin version is not support 1.12.2
