### ISSUE TITLE
[1.12.2] Start with JDK17

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#361]
jdk17/bin/java -jar server.jar
```[18:11:35] [main/ERROR]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /home/server/. for Forge Mod Loader
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:112) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:88) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:64) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at catserver.server.launch.Java11Launch.launch(Java11Launch.java:97) [server.jar:git-CatServer-1.12.2-e157f25]
        at catserver.server.launch.Java11Launch.main(Java11Launch.java:22) [server.jar:git-CatServer-1.12.2-e157f25]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [server.jar:git-CatServer-1.12.2-e157f25]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at catserver.server.CatServerLaunch.main(CatServerLaunch.java:13) [server.jar:git-CatServer-1.12.2-e157f25]
Caused by: java.lang.ExceptionInInitializerError
        at ua.agravaine.hooklib.minecraft.HookLoader.<clinit>(HookLoader.java:21) ~[HookLoader.class:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:515) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:439) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:253) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:108) ~[server.jar:git-CatServer-1.12.2-e157f25]
        ... 16 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @3bd418e4
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at ua.agravaine.hooklib.asm.ClassMetadataReader.<clinit>(ClassMetadataReader.java:23) ~[ClassMetadataReader.class:?]
        at ua.agravaine.hooklib.minecraft.HookLoader.<clinit>(HookLoader.java:21) ~[HookLoader.class:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:515) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:439) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:253) ~[server.jar:git-CatServer-1.12.2-e157f25]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:108) ~[server.jar:git-CatServer-1.12.2-e157f25]
        ... 16 more
```

**Comment by Luohuayu** [comment]
It looks like the mod doesn't support jdk17, i do not have a solution now

**Comment by Luohuayu** [comment]
https://stackoverflow.com/questions/66974846/java-lang-exceptionininitializererror-with-java-16-j-l-classformaterror-access
https://stackoverflow.com/questions/68168691/java-lang-reflect-inaccessibleobjectexception-unable-to-make-protected-final-ja

**Comment by dayd21git** [comment]
> It looks like the mod doesn't support jdk17, i do not have a solution now

Don't you think that this is an obvious problem and letting the server work with JAVA17 is not a good idea?

**Comment by Luohuayu** [comment]
> 
> 
> > It looks like the mod doesn't support jdk17, i do not have a solution now
> 
> Don't you think that this is an obvious problem and letting the server work with JAVA17 is not a good idea?

So I recommend Java8

**Comment by Fox2Code** [comment]
https://github.com/Karlatemp/UnsafeAccessor <- This might be the solution to the mod compatibility issue.
It also has an api to add opens here, could be useful to fix mod compatibility on recent JDKs ->
https://github.com/Karlatemp/UnsafeAccessor/blob/1e019030c7f75960bac532e61d158d8e2ebb697b/api/src/main/java/io/github/karlatemp/unsafeaccessor/ModuleAccess.java#L87

**Comment by XionioXMaster** [comment]
https://forums.minecraftforge.net/topic/106103-minecraft-1165-forge-server-wont-start/

Насколько я помню, даже официально Forge заявлял что 16+ Java не будет работать на 1.16.5 Forge

**Comment by dayd21git** [comment]
> https://forums.minecraftforge.net/topic/106103-minecraft-1165-forge-server-wont-start/
> 
> Насколько я помню, даже официально Forge заявлял что 16+ Java не будет работать на 1.16.5 Forge

И совсем не смущает, что тема открыта под версию 1.12.2?
А что касается гибридов Forge1.16.5/Spigot и Java16, то на практике существует далеко не одно ядро гибридное и, если память не изменяет, некоторые из таких ядер стартуют как раз только под JAVA16+, но могу ошибаться(давно было)
