### ISSUE TITLE
BetterRTP-3.2.1-3 Plugin Cannot find main class

### ISSUE THREAD

**Issue by speccycy** [Luohuayu/CatServer#364]
I have reported this problem to the developer of this plugin.
But they can't fix it.

if you can fix it thank you in advance

BetterRTP-3.2.1-3
CatServer-d1fba12-universal

Error log
```
[18:07:02] [Server thread/ERROR] [Minecraft]: Could not load 'plugins\BetterRTP-3.2.1-3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.SuperRonanCraft.BetterRTP.BetterRTP'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[PluginClassLoader.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-d1fba12]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.ClassNotFoundException: Failed to remap class me.SuperRonanCraft.BetterRTP.BetterRTP
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:229) ~[PluginClassLoader.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[PluginClassLoader.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-d1fba12]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_302]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_302]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_302]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_302]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-d1fba12]
	... 8 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:228) ~[JarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:194) ~[PluginClassLoader.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[PluginClassLoader.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-d1fba12]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_302]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_302]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_302]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_302]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-d1fba12]
	... 8 more
```

**Comment by speccycy** [comment]
BetterRTP-3.2.1-4 in the new update is now available.
