### ISSUE TITLE
Myworlds Plugin bug - enum is null

### ISSUE THREAD

**Issue by speccycy** [Luohuayu/CatServer#366]
**Myworlds Plugin is not working due to enum is null**

plugins dev has already solved some of the problem ,But it still have the problem

CatServer-d1fba12-universal
MyWorlds-1.17.1-v2-SNAPSHOT-96
BKCommonLib-1.17.1-v5-SNAPSHOT-1130

**the relevant source code** 
https://github.com/bergerhealer/MyWorlds/blob/master/src/main/java/com/bergerkiller/bukkit/mw/WorldMode.java#L56

**Dev comment**
![image](https://user-images.githubusercontent.com/68125477/136534215-b7e8051a-c592-4042-9386-48aae3e07111.png)

```
[04:15:01] [Server thread/ERROR] [com.bergerkiller.bukkit.mw.MyWorlds]: [My_Worlds] An error occurred while enabling, the plugin will be disabled:
java.lang.NullPointerException: null
    at com.bergerkiller.bukkit.mw.WorldMode.<init>(WorldMode.java:59) ~[MyWorlds-1.17.1-v2-SNAPSHOT-95.jar:?]
    at com.bergerkiller.bukkit.mw.WorldMode.get(WorldMode.java:141) ~[MyWorlds-1.17.1-v2-SNAPSHOT-95.jar:?]
    at com.bergerkiller.bukkit.mw.WorldMode.get(WorldMode.java:145) ~[MyWorlds-1.17.1-v2-SNAPSHOT-95.jar:?]
    at com.bergerkiller.bukkit.mw.WorldConfig.loadDefaults(WorldConfig.java:102) ~[MyWorlds-1.17.1-v2-SNAPSHOT-95.jar:?]
    at com.bergerkiller.bukkit.mw.WorldConfigStore.create(WorldConfigStore.java:25) ~[MyWorlds-1.17.1-v2-SNAPSHOT-95.jar:?]
    at com.bergerkiller.bukkit.mw.WorldConfigStore.get(WorldConfigStore.java:50) ~[MyWorlds-1.17.1-v2-SNAPSHOT-95.jar:?]
    at com.bergerkiller.bukkit.mw.WorldConfigStore.get(WorldConfigStore.java:62) ~[MyWorlds-1.17.1-v2-SNAPSHOT-95.jar:?]
    at com.bergerkiller.bukkit.mw.WorldConfigStore.init(WorldConfigStore.java:147) ~[MyWorlds-1.17.1-v2-SNAPSHOT-95.jar:?]
    at com.bergerkiller.bukkit.mw.MyWorlds.enable(MyWorlds.java:266) ~[MyWorlds-1.17.1-v2-SNAPSHOT-95.jar:?]
    at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:857) [BKCommonLib-1.17.1-v5-SNAPSHOT-1130.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [JavaPlugin.class:git-CatServer-1.12.2-d1fba12]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-d1fba12]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-d1fba12]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436) [CraftServer.class:git-CatServer-1.12.2-d1fba12]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-d1fba12]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [nz.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
```

**Comment by bergerkiller** [comment]
Specifically, the .toString() is rewritten by the server into something that causes an NPE. Type itself isn't null as I checked for that in the for loop.

**Comment by Luohuayu** [comment]
Upload full log

**Comment by speccycy** [comment]
> Upload full log

https://paste.traincarts.net/amodatuzam.makefile
https://gist.github.com/speccycy/fcb76c0cade79238f166c3d29471b736
