### ISSUE TITLE
[1.12.2] 不兼容模组报错

### ISSUE THREAD

**Issue by fkh233** [Luohuayu/CatServer#376]
[15:03:09] [Server thread/ERROR]: A TileEntity ec:utb(com.blakebr0.extendedcrafting.tile.TileUltimateCraftingTable) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException: null
        at com.blakebr0.extendedcrafting.tile.StandardTable.setResult(StandardTable.java:58) ~[StandardTable.class:?]
        at com.blakebr0.extendedcrafting.tile.StandardTable.updateResult(StandardTable.java:68) ~[StandardTable.class:?]
        at com.blakebr0.extendedcrafting.tile.StandardTable.func_145839_a(StandardTable.java:51) ~[StandardTable.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:128) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:498) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:git-CatServer-1.12.2-119130c]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:95) [ChunkIOExecutor.class:git-CatServer-1.12.2-119130c]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:96) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) [on.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:268) [CraftWorld.class:git-CatServer-1.12.2-119130c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:225) [CraftWorld.class:git-CatServer-1.12.2-119130c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:708) [CraftWorld.class:git-CatServer-1.12.2-119130c]
        at org.bukkit.Location.getBlock(Location.java:91) [Location.class:git-CatServer-1.12.2-119130c]
        at cz._heropwp.playerworldspro.d.h.b(WorldManager.java:648) [PlayerWorldsPro-5.2.4_hotfix%20(1).jar:?]
        at cz._heropwp.playerworldspro.d.h.a(WorldManager.java:582) [PlayerWorldsPro-5.2.4_hotfix%20(1).jar:?]
        at cz._heropwp.playerworldspro.b.e.a(GUI_Main.java:325) [PlayerWorldsPro-5.2.4_hotfix%20(1).jar:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor317.execute(Unknown Source) [?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) [EventExecutor$2.class:git-CatServer-1.12.2-119130c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:git-CatServer-1.12.2-119130c]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-119130c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-119130c]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2168) [pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) [lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) [lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_301]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:890) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]

**Comment by Luohuayu** [comment]
插件或MOD触发区块无限递归加载, 建议排查后反馈相应作者
