### ISSUE TITLE
[1.12.2] mythicmobs條件moving true使用後會報錯

### ISSUE THREAD

**Issue by toretgman** [Luohuayu/CatServer#379]
[19:39:41] [Craft Scheduler Thread - 2374/WARN]: [MythicMobs] Plugin MythicMobs v4.7.2-FREE generated an exception while executing task 888
java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to net.minecraft.entity.EntityLiving
        at io.lumine.xikage.mythicmobs.volatilecode.v1_12_R1.VolatileEntityHandler_v1_12_R1.isEntityInMotion(VolatileEntityHandler_v1_12_R1.java:79) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.conditions.all.MovingCondition.check(MovingCondition.java:24) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.SkillCondition.lambda$evaluateTargets$19(SkillCondition.java:137) ~[?:?]
        at java.util.Collection.removeIf(Unknown Source) ~[?:1.8.0_291]
        at io.lumine.xikage.mythicmobs.skills.SkillCondition.evaluateTargets(SkillCondition.java:135) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.Skill.usable(Skill.java:208) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.Skill.isUsable(Skill.java:282) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.mechanics.MetaSkillMechanic.cast(MetaSkillMechanic.java:72) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.executeSkills(SkillMechanic.java:309) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.execute(SkillMechanic.java:264) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.SkillManager.executeMobTimerSkills(SkillManager.java:349) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.SkillManager.runTimerSkills(SkillManager.java:331) ~[?:?]
        at io.lumine.xikage.mythicmobs.clock.MythicMobsAsyncClock.run(MythicMobsAsyncClock.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-119130c]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-119130c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_291]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

**Comment by Luohuayu** [comment]
未排查到原因
推测是当前SpecialSource库版本对lambda的兼容差导致问题
`at java.util.Collection.removeIf(Unknown Source) ~[?:1.8.0_291]`
因为无法升级SpecialSource库进行测试, 暂时无法修复
