### ISSUE TITLE
Encoded string too long.

### ISSUE THREAD

**Issue by Zilacon** [Luohuayu/CatServer#390]
When saving the world on the MC Eternal modpack it throws this error:

```
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: java.io.UTFDataFormatException: encoded string too long: 790879 bytes
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.nbt.NBTTagString.func_74734_a(NBTTagString.java:25)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:470)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:30)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:470)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:30)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.nbt.CompressedStreamTools.func_74799_a(CompressedStreamTools.java:47)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.world.storage.MapStorage.lambda$saveData$0(MapStorage.java:128)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at net.minecraft.world.storage.MapStorage$$Lambda$6893/0x0000000000000000.run(Unknown Source)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:37:08] [CatServer Async Task Handler Thread - 0/WARN] []: 	at java.lang.Thread.run(Thread.java:826)
```

This error seems to have been reported to mojang here: https://bugs.mojang.com/browse/MC-83313
Is there any chance of fixing this?

**Comment by Luohuayu** [comment]
It seems that the mod is writing too much NBT? You can try to modify the limit and build.

**Comment by Zilacon** [comment]
How would i modify the limit without modifying the mod?

**Comment by Luohuayu** [comment]
Can't seem to modify it without modifying the mod. This is a limit of Java.
I really can't figure out why there is such a long string. You may need to debug it.

![1](https://user-images.githubusercontent.com/29095770/164531411-3e5e7dfd-6d5e-42d1-9617-385cb132b653.jpg)
![2](https://user-images.githubusercontent.com/29095770/164531420-e06971f5-8a45-44a4-9e72-47cebd82f5e6.jpg)

**Comment by Luohuayu** [comment]
I've added an exception message that might be useful to you.
https://github.com/Luohuayu/CatServer/commit/9ae5c53ac1dd9e8141d88e7730635777df088e55

**Comment by Zilacon** [comment]
This error seems to be gone since i updated. Ill close for now, thanks.
