### ISSUE TITLE
熔炉咯嘣

### ISSUE THREAD

**Issue by Laotouy** [Luohuayu/CatServer#4]
https://paste.ubuntu.com/p/R2dYhd9tBJ/

**Comment by Laotouy** [comment]
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Calendar.getDisplayName(Unknown Source)
	at java.text.SimpleDateFormat.subFormat(Unknown Source)
	at java.text.SimpleDateFormat.format(Unknown Source)
	at java.text.SimpleDateFormat.format(Unknown Source)
	at java.text.DateFormat.format(Unknown Source)
	at net.minecraft.advancements.CriterionProgress.func_192148_e(SourceFile:55)
	at net.minecraft.advancements.AdvancementProgress$Serializer.serialize(SourceFile:225)
	at net.minecraft.advancements.AdvancementProgress$Serializer.serialize(SourceFile:217)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at com.google.gson.Gson.toJson(Gson.java:603)
	at com.google.gson.Gson.toJson(Gson.java:583)
	at net.minecraft.advancements.PlayerAdvancements.func_192749_b(PlayerAdvancements.java:190)
	at net.minecraft.server.management.PlayerList.func_72391_b(PlayerList.java:465)
	at net.minecraft.server.management.PlayerList.func_72389_g(PlayerList.java:1576)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:807)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:638)
	at java.lang.Thread.run(Unknown Source)


 不知名q
