### ISSUE TITLE
[1.18] Startup error

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#408]
**Environment**

Minecraft version(1.18.2): 
Build version(Get from /version command): CatServer-1.18.2-3b94946-server
Mods/Plugins: -

**Describe the bug**

C:\Users\DeZoWaRe\Desktop\Новая папка (6)>java -server -Xms128M -Xmx2000M -jar server.jar
Loading libraries, please wait...
Unpacking vanilla server jar..
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
        at net.minecraftforge.installertools.ConsoleTool.<clinit>(ConsoleTool.java:31)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at foxlaunch.Utils.relaunch(Utils.java:87)
        at foxlaunch.legacy.InstallTool.install(InstallTool.java:106)
        at foxlaunch.FoxServerLauncher.main(FoxServerLauncher.java:21)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 6 more

C:\Users\DeZoWaRe\Desktop\Новая папка (6)>pause
Для продолжения нажмите любую клавишу . . .

**Screenshot/Video**
![image](https://user-images.githubusercontent.com/86433158/165268333-3f23ed5c-ac7a-451f-b347-07fe16670603.png)

**Comment by Luohuayu** [comment]
Fixed. With this version it is possible to start, but there are no features available yet and there are serious issues.
https://jenkins.rbqcloud.cn:30011/job/CatServer-1.18.2/15/
Of course, everyone is welcome to contribute to the code.
