### ISSUE TITLE
[1.12.2] ShinColle 后台报错

### ISSUE THREAD

**Issue by MoeShimaKaze** [Luohuayu/CatServer#433]
**运行环境** Win Server 2019

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): git-CatServer-1.12.2-1f1c21e (MC: 1.12.2)
相关模组/插件: ShinColle

**描述这个BUG**
后台报错，概率性的导致玩家刷物品
(如果有报错请附上pastebin链接或上传日志文件)
`[01:29:52] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:258) [ol.class:?]
        at net.minecraftforge.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:376) [EntityRegistry.class:git-CatServer-1.12.2-1f1c21e]
        at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:80) [ol.class:?]
        at net.minecraft.world.ServerWorldEventHandler.func_72703_a(ServerWorldEventHandler.java:37) [op.class:?]
        at net.minecraft.world.World.func_72923_a(World.java:1459) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1331) [oo.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1133) [amu.class:?]
        at com.lulan.shincolle.item.ShipSpawnEgg.func_77659_a(ShipSpawnEgg.java:571) [ShipSpawnEgg.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:237) [aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:431) [or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:1211) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) [mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) [mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_311]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_311]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:226) ~[ol.class:?]
        ... 21 more`
**导致的问题r**
玩家的舰娘死后概率复制自己的舰娘，导致可通过舰娘背包刷物品
**复现方法**
放出舰娘，杀死舰娘，重新放置，后台就会报错
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
还是用一下Pastebin吧， 这个都乱的不成样子了

**Comment by MoeShimaKaze** [comment]
> 还是用一下Pastebin吧， 这个都乱的不成样子了

https://paste.fastmirror.net/?dd0896eaf294e368#HoTTUYyvx7uVS3wcqFdWwymiwRkZxUzUMdgERbGnkT5T
已上传

**Comment by Luohuayu** [comment]
https://github.com/MoeShimaKaze/ShinColle/blob/mc-1.12.2/src/main/java/com/lulan/shincolle/entity/BasicEntityShip.java
https://github.com/MoeShimaKaze/ShinColle/blob/mc-1.12.2/src/main/java/com/lulan/shincolle/item/ShipSpawnEgg.java

**Comment by MoeShimaKaze** [comment]
在Forge Server上无法复现

**Comment by MoeShimaKaze** [comment]
> 

经过测试，在ForgeServer上无法复现
Forge版本2860

**Comment by Luohuayu** [comment]
同#204, PlayerEvent.Clone事件无法正确处理

**Comment by MoeShimaKaze** [comment]
> 
好的，等候大佬修复
