### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by nkomarn** [Luohuayu/CatServer#44]
Every time I try to start CatServer, I get this error:

`We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:44)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at catserver.server.CatServerLaunch.main(CatServerLaunch.java:6)`

**Comment by Becods** [comment]
You need to add library files, but Luohuayu doesn't provide them in releases
Maybe it will auto download and load, you just need to wait

**Comment by LinuxZombie-Sys** [comment]
Make this into a run.bat and then rename your jarfile: to CatServer then run it
`@ECHO OFF
java -Xms4024M -Xmx4048M -jar CatServer.jar nogui
pause`

**Comment by Luohuayu** [comment]
If you setup and build the project yourself, need to copy the libraries into the project root directory (Except minecraft_server.1.12.2.jar)
https://github.com/Luohuayu/CatServerRes/blob/master/libraries.zip

**Comment by AfonsoBatista7** [comment]
https://github.com/Luohuayu/CatServerRes/blob/master/libraries.zip link is not available anymore... how do I go around this problem?
