### ISSUE TITLE
[1.16.5] 崩溃

### ISSUE THREAD

**Issue by zfms4188** [Luohuayu/CatServer#451]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.16.5
构建版本(从/version指令获取): 1.16.5-87a458d6
相关模组/插件:  ae2 kubejs

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://pastebin.com/eF7WaEsV
**导致的问题r**
服务器崩溃
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
需要完整日志

**Comment by zfms4188** [comment]
> 需要完整日志

https://mkt.lanzoul.com/i1WPT05lxocb
里面还有个区块的报错喃

**Comment by zfms4188** [comment]
保存区块报错
`[13:39:10] [Server thread/ERROR]: Failed to save chunk [-20, 42]
 java.util.concurrent.CompletionException: java.lang.ClassCastException: class io.alwa.mods.myrtrees.common.blockentity.FilledRubberwoodLogBlockEntity cannot be cast to class net.minecraft.entity.Entity (io.alwa.mods.myrtrees.common.blockentity.FilledRubberwoodLogBlockEntity and net.minecraft.entity.Entity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @1ddc6db2)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:394) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:372) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:379) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:447) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1050) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:942) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassCastException: class io.alwa.mods.myrtrees.common.blockentity.FilledRubberwoodLogBlockEntity cannot be cast to class net.minecraft.entity.Entity (io.alwa.mods.myrtrees.common.blockentity.FilledRubberwoodLogBlockEntity and net.minecraft.entity.Entity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @1ddc6db2)
        at net.minecraft.world.server.ServerWorld.redirect$zef000$onEntityRemoved(ServerWorld.java:2330) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_217466_a(ServerWorld.java:1046) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_219185_a(ChunkManager.java:415) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        ... 11 more`

**Comment by ShangguanJumern** [comment]
请问这个错误是怎么解决的？

**Comment by Kotori0629** [comment]
> 请问这个错误是怎么解决的？

未解决，如有遇到一样的问题 麻烦新开一个issues
