### ISSUE TITLE
[1.18.2] 我无法构建1.18.2服务器

### ISSUE THREAD

**Issue by YongAn404** [Luohuayu/CatServer#455]
我无法构建1.18.2服务器

> Task :clean:extractRangeMap FAILED
Exception in thread "main" java.lang.IllegalArgumentException: Invalid input value: C:\Users\yongan404\CatServer\projects\clean\src\main\java
        at net.minecraftforge.srg2source.api.RangeExtractorBuilder.input(RangeExtractorBuilder.java:157)
        at net.minecraftforge.srg2source.api.RangeExtractorBuilder.input(RangeExtractorBuilder.java:151)
        at net.minecraftforge.srg2source.RangeExtractMain.lambda$main$1(RangeExtractMain.java:108)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
        at net.minecraftforge.srg2source.RangeExtractMain.main(RangeExtractMain.java:106)
        at net.minecraftforge.srg2source.ConsoleTool$Redefined.main(ConsoleTool.java:115)
        at net.minecraftforge.srg2source.ConsoleTool.main(ConsoleTool.java:48)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clean:extractRangeMap'.
> Process 'command 'C:\Program Files\Java\jdk-17.0.2\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 16s
11 actionable tasks: 8 executed, 3 up-to-date

**Comment by Kotori0629** [comment]
setup buildCatServer
