### ISSUE TITLE
[1.12.2] 服务端偶尔会出现这段报错

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#477]
**运行环境**

最新版本cat核心

[10:35:51] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:424) ~[?:1.8.0_291]
        at java.util.ArrayList.get(ArrayList.java:437) ~[?:1.8.0_291]
        at net.minecraft.inventory.Container.func_75139_a(Container.java:207) ~[afr.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2105) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by Luohuayu** [comment]
无任何有效信息 请按照标准模板反馈
