### ISSUE TITLE
LibsDisguises伪装无法使用

### ISSUE THREAD

**Issue by CHHBlock** [Luohuayu/CatServer#5]
用的是社区交流群(现)里面的修复版，在稳定版内可以正常运行，换成pro或多线程之后无法使用，输入/d 生物之后后台会报错
`java.lang.NoSuchFieldException: trackedPlayerMap
at java.lang.Class.getDeclaredField(Class.java:2070)
at catserver.server.remapper.ReflectionMethods.getDeclaredField(ReflectionMethods.java:36)
at me.libraryaddict.disguise.utilities.ReflectionManager.getNmsField(ReflectionManager.java:458)
at me.libraryaddict.disguise.utilities.ReflectionManager.getNmsField(ReflectionManager.java:471)
at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:1393)
at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:1567)
at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:830)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:638)
at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:1394)
at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:1567)
at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:830)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:638)
at java.lang.Thread.run(Thread.java:748)`
过一段时间玩家会隐身但不会显示伪装，输入/u取消伪装也会有这个报错
但是用于mythicmobs怪物伪装就没有任何问题

**Comment by Luohuayu** [comment]
请使用稳定版或者反馈插件作者
