### ISSUE TITLE
[1.16.5]  plasmo-voice

### ISSUE THREAD

**Issue by SqdGoodlol** [Luohuayu/CatServer#509]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2):  1.16.5
Build version(Get from /version command): CatServer-1.16.5-9d5e91ab-server
Mods/Plugins: 
plasmo-voice

**Describe the bug**
[09:02:09] [Craft Scheduler Thread - 6/WARN]: [PlasmoVoice] Plugin PlasmoVoice v1.0.10 generated an exception while executing task 307
 java.lang.NoSuchMethodError: 'void su.plo.voice.common.packets.tcp.ConfigPacket.<init>(int, java.util.List, int, int, int, int, boolean)'
        at su.plo.voice.listeners.PluginChannelListener.lambda$onPluginMessageReceived$0(PluginChannelListener.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [forge:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Expected behavior**

**To Reproduce**
Install plugin. Go to the server with the mod. Try to connect

**Screenshot/Video**
![image](https://user-images.githubusercontent.com/86075284/176604155-ea33318d-8c93-4782-a723-0c194ac8c36e.png)

(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
Give me this plugin, and depends

**Comment by SqdGoodlol** [comment]
https://www.spigotmc.org/resources/plasmo-voice-server.91064/

https://github.com/plasmoapp/plasmo-voice/releases

**Comment by XionioXMaster** [comment]
> 

Why would a mod server use a plugin when there is a mod for Forge. which actually works...
