### ISSUE TITLE
ASYNC PAPI弹警告

### ISSUE THREAD

**Issue by LDS-XiaoYe** [Luohuayu/CatServer#51]
papi版本:2.9.2
catserver-async 版本 CatServerAsync-1.12.2-76aa211

警告原文：
[PlaceholderAPI] Plugin PlaceholderAPI v2.9.2 generated an exception while executing task 27
java.lang.NullPointerException: null
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager$1.run(ExpansionCloudManager.java:257) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServerAsync-1.12.2-76aa211]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServerAsync-1.12.2-76aa211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
>ver

**Comment by Luohuayu** [comment]
网络问题
