### ISSUE TITLE
[1.16.5]Could not pass event PlayerInteractEvent to TrMenu v3.1.10

### ISSUE THREAD

**Issue by fengyoun** [Luohuayu/CatServer#515]
[16:47:50] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to TrMenu v3.1.10
 java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor149.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:578) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:430) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:397) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:393) ~[forge:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_175087_a(ServerPlayNetHandler.java:1822) ~[?:?]
        at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:31) ~[?:?]
        at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:9) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:886) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:869) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:863) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:849) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:781) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.InventoryView.getTopInventory()" because the return value of "org.bukkit.entity.Player.getOpenInventory()" is null
        at me.arasple.mc.trmenu.module.internal.listener.ListenerItemInteract.onInteract(ListenerItemInteract.kt:36) ~[?:?]
        ... 33 more

**Comment by Kotori0629** [comment]
复现流程呢，补充后重新发布
