### ISSUE TITLE
[1.12.2] Could not pass event InventoryCreativeEvent to Vegas v3.0

### ISSUE THREAD

**Issue by speccycy** [Luohuayu/CatServer#532]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.12.2
Build version(Get from /version command): CatServer-6eb82ffe-universal
Mods/Plugins: Vegas Plugin

**Describe the bug**
(If there is an error, please attach the pastebin link)
Spam Error

```
[12:01:04] [Server thread/ERROR] [Minecraft]: Could not pass event InventoryCreativeEvent to Vegas v3.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:69) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
	at net.minecraft.network.NetHandlerPlayServer.processCreativeInventoryAction(NetHandlerPlayServer.java:2383) [pa.class:?]
	at net.minecraft.network.play.client.CPacketCreativeInventoryAction.processPacket(CPacketCreativeInventoryAction.java:29) [lw.class:?]
	at net.minecraft.network.play.client.CPacketCreativeInventoryAction.processPacket(CPacketCreativeInventoryAction.java:11) [lw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_331]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_331]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:910) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_331]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.event.inventory.InventoryType.GRINDSTONE
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_331]
	at org.bukkit.event.inventory.InventoryType.valueOf(InventoryType.java:3) ~[InventoryType.class:git-CatServer-1.12.2-6eb82ffe]
	at org.shimado.VEGASlisteners.TableCasinoListener.checkTableClick(TableCasinoListener.java:195) ~[?:?]
	at catserver.server.executor.asm.generated.GeneratedEventExecutor304.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
	... 15 more
```

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
1.12.2 does not have InventoryType **GRINDSTONE**

GRINDSTONE add in 1.14-pre5 : https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/diff/src/main/java/org/bukkit/event/inventory/InventoryType.java?until=67d908a9830c71267ee740f5bddd728ce9c64cc7

**Comment by Kotori0629** [comment]
You should reduce the plugin version to support the 1.12.2 server
