### ISSUE TITLE
[1.16.5] bountifulbaubles引起崩溃

### ISSUE THREAD

**Issue by SherkeyXD** [Luohuayu/CatServer#535]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 1.16.5-2b1466f6
相关模组/插件: 
> ActuallyAdditions-1.16.5-1.1.52.130.jar
AIReducer-1.16-0.1.0.jar
AoA3-1.16.5-3.6.6.jar
architectury-1.32.66.jar
AttributeFix-1.16.5-10.1.4.jar
AutoRegLib-1.6-49.jar
bettercompat-0.4.2-1.16.5-36.2.34.jar
betterendforge-1.16.5-1.6.3.jar
Botania-1.16.5-420.2.jar
bountifulbaubles-1.16.5-0.1.0-forge.jar
citadel-1.8.1-1.16.5.jar
constructsarmory-forge-2.0.0-alpha.2+1.16.5.jar
create-mc1.16.5_v0.3.2g.jar
curios-forge-1.16.5-4.0.5.3.jar
DungeonCrawl-1.16.5-2.3.9.jar
FastLeafDecay-v25.2.jar
flywheel-1.16-0.2.5.jar
ftb-backups-2.1.2.2.jar
ftb-library-forge-1605.3.4-build.90.jar
ftb-ultimine-forge-1605.3.1-build.45.jar
iceandfire-2.1.10-1.16.5.jar
Jade-1.16.4-2.8.2.jar
jei-1.16.5-7.7.1.152.jar
journeymap-1.16.5-5.8.5p5.jar
lycanitesmobs-1.16.5-2.3.3.3.jar
Mantle-1.16.5-1.6.157.jar
materialis-1.16.5-2.5.1.jar
ModernUI-1.16.5-2.7.1.105-universal.jar
pamhc2foodcore-1.16.3-1.0.2.jar
Patchouli-1.16.4-53.3.jar
performant-1.16.2-5-3.98m.jar
randompatches-2.4.4-forge.jar
starlight-forge-1.0.0-RC2-1.16.5.jar
taiga-1.16.5-1.0.0.jar
TConstruct-1.16.5-3.3.4.335.jar
TravelersBackpack-1.16.5-5.4.12.jar
traverse-1.16.4-0.4.3.8.jar

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
服务器启动时直接崩溃
log: 
```java
Loading libraries, please wait...
[21:27:00] [main/INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.35, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[21:27:00] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 11.0.15.11 by Alibaba
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/home/ubuntu/minecraft/libraries/cpw/mods/modlauncher/8.1.3/modlauncher-8.1.3.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[21:27:00] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[21:27:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/ubuntu/minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[21:27:00] [main/INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:27:00] [main/INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:27:00] [main/INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:27:00] [main/INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:27:00] [main/INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:27:00] [main/INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:27:00] [main/INFO]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[21:27:00] [main/INFO]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[21:27:00] [main/INFO]: Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[21:27:00] [main/INFO]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[21:27:00] [main/INFO]: Successfully loaded Mixin Connector [icyllis.modernui.forge.MixinConnector]
[21:27:01] [main/INFO]: Compatibility level set to JAVA_11
[21:27:01] [main/INFO]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[21:27:01] [main/INFO]: Performant configs loaded
[21:27:01] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[21:27:01] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.world.WorldMixin as config disables it.
[21:27:01] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
Exception in thread "main" [21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.reflect.InvocationTargetException
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at foxlaunch.FoxServerLauncher.main(FoxServerLauncher.java:33)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at catserver.server.CatServerLaunch.main(CatServerLaunch.java:8)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[21:27:01] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: 	... 6 more
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:648]: Caused by: java.lang.reflect.InvocationTargetException
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:648]: 	... 13 more
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at net.minecraft.server.MinecraftServer.<clinit>(MinecraftServer.java:172)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	at net.minecraft.server.Main.main(Main.java:103)
[21:27:01] [main/INFO]: [java.lang.Throwable:printStackTrace:671]: 	... 19 more
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method onApplyDamageAmount(FLnet/minecraft/util/DamageSource;)F in bountifulbaubles.mixins.json:MixinPlayerEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bountifulbaubles-common-refmap.json
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[21:27:01] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	... 36 more
```

**导致的问题**
服务器无法启动，但在本地运行相同mod没有问题
**复现方法**
使用bountifulbaubles-1.16.5-0.1.0-forge.jar模组
**截图/视频**
(如果没有可以忽略)

**Comment by SherkeyXD** [comment]
对了 java 用的是 drogonwell 11，是否有影响？

**Comment by SherkeyXD** [comment]
问题根源找到，由bountifulbaubles-1.16.5-0.1.0-forge.jar引起

**Comment by Kotori0629** [comment]
不会兼容了

**Comment by Dreamail** [comment]
用release和jenkins里的1.16.5构建还是报一样的错
