### ISSUE TITLE
GravitLauncher + Catserver

### ISSUE THREAD

**Issue by SqdGoodlol** [Luohuayu/CatServer#538]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): This server is running CatServer version 1.16.5-caa59bdd (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
Mods/Plugins: 

**Describe the bug**
Connected the server to the gravit launcher and gives an error

**Expected behavior**
C:\Users\danil\Desktop\testserver>"C:\Program Files\Java\jdk-17.0.2\bin\java.exe" -javaagent:ServerWrapper.jar -Dserverwrapper.agentproxy=foxlaunch.legacy.JarLoader -cp ServerWrapper.jar;CatServer-1.16.5.jar pro.gravit.launcher.server.ServerWrapper
GravitLauncher (fork sashok724's Launcher) ServerWrapper v5.2.8-1 stable (build #1)
License for ServerWrapper GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022.08.02 10:50:06 [WARN] Not connected to ServerProfile. May be serverName incorrect?
2022.08.02 10:50:06 [INFO] ServerWrapper: LaunchServer address: ws://localhost:9274/api. Title: unknown
2022.08.02 10:50:06 [INFO] Minecraft Version (for profile): unknown
2022.08.02 10:50:06 [INFO] Start Minecraft Server
Loading libraries, please wait...
[10:50:06] [main/INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.35, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[10:50:06] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17.0.2 by Oracle Corporation
[10:50:06] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[10:50:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/danil/Desktop/testserver/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[10:50:07] [main/INFO]: Launching target 'fmlserver' with arguments [--gameDir, .]
[10:50:11] [modloading-worker-0/INFO]: Forge mod loading, version 36.2.35, for MC 1.16.5 with MCP 20210115.111550
[10:50:11] [modloading-worker-0/INFO]: MinecraftForge v36.2.35 Initialized
[10:50:13] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:50:14] [main/INFO]: Reloading ResourceManager: Default, forge-1.16.5-36.2.35-universal.jar, bukkit
[10:50:15] [Worker-Main-9/INFO]: Loaded 927 advancements
[10:50:16] [Server thread/INFO]: Starting minecraft server version 1.16.5
[10:50:16] [Server thread/INFO]: Loading properties
[10:50:16] [Server thread/INFO]: Default game type: SURVIVAL
[10:50:16] [Server thread/INFO]: Generating keypair
[10:50:16] [Server thread/INFO]: Starting Minecraft server on *:25565
[10:50:16] [Server thread/INFO]: Using default channel type
[10:50:17] [Server thread/INFO]: This server is running CatServer version 1.16.5-caa59bdd (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
[10:50:17] [Server thread/INFO]: Debug logging is enabled
[10:50:17] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:50:17] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:50:18] [Server thread/INFO]: Preparing level "world"
[10:50:18] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:50:18] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[10:50:19] [Server thread/INFO]: Preparing spawn area: 0%
[10:50:20] [Server thread/INFO]: Preparing spawn area: 62%
[10:50:23] [Worker-Main-8/INFO]: Preparing spawn area: 83%
[10:50:25] [Worker-Main-11/INFO]: Preparing spawn area: 84%
[10:50:26] [Worker-Main-14/INFO]: Preparing spawn area: 94%
[10:50:26] [Server thread/INFO]: Time elapsed: 7780 ms
[10:50:26] [Server thread/INFO]: Done (8.096s)! For help, type "help"
[10:51:27] [User Authenticator #1/INFO]: Disconnecting /127.0.0.1:57914: Failed to verify username!
[10:51:27] [User Authenticator #1/ERROR]: Username 'Goodlol' tried to join with an invalid session

**To Reproduce**
Make a launcher. Connect to the server. Try to come in.
**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
`
2022.08.02 10:50:06 [WARN] Not connected to ServerProfile. May be serverName incorrect?
2022.08.02 10:50:06 [INFO] ServerWrapper: LaunchServer address: ws://localhost:9274/api. Title: unknown
2022.08.02 10:50:06 [INFO] Minecraft Version (for profile): unknown
`

**Comment by XionioXMaster** [comment]
> 

Детально объясни как подключал, сбрось конфиг лаунч-сервера и уточни от куда клиент, есть ли auhtlib клиента в CatServer?

**Comment by XionioXMaster** [comment]
Обрати внимание что подключения к профилю нет
### **2022.08.02 10:50:06 [WARN] Not connected to ServerProfile. May be serverName incorrect?**

**Comment by SqdGoodlol** [comment]
![image](https://user-images.githubusercontent.com/86075284/182335922-aacee9c7-52ba-4644-b420-d448b84dd291.png)

**Comment by SqdGoodlol** [comment]
Well, according to the instructions. "C:\Program Files\Java\jdk-17.0.2\bin\java.exe" -javaagent:ServerWrapper.jar -Dserverwrapper.agentproxy=foxlaunch.legacy.JarLoader -cp ServerWrapper.jar;CatServer-1.16.5.jar pro.gravit.launcher.server.ServerWrapper

**Comment by SqdGoodlol** [comment]
{
  "address": "ws://localhost:9274/api",
  "serverName": "Goldenbaton",
  "autoloadLibraries": false,
  "classpath": [],
  "classLoaderConfig": "SYSTEM_ARGS",
  "mainclass": "catserver.server.CatServerLaunch",
  "args": [],
  "oauthExpireTime": 0,
  "extendedTokens": {
    "checkServer": "*token*"
  },
  "env": "STD"
}

**Comment by SqdGoodlol** [comment]
"C:\Program Files\Java\jdk-17.0.2\bin\java.exe" -javaagent:ServerWrapper.jar -Dserverwrapper.agentproxy=foxlaunch.legacy.JarLoader -cp ServerWrapper.jar;CatServer-1.16.5.jar pro.gravit.launcher.server.ServerWrapper

**Comment by SqdGoodlol** [comment]
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by SqdGoodlol** [comment]
Я починил

**Comment by SqdGoodlol** [comment]
C:\Users\danil\Desktop\testserver>"C:\Program Files\Java\jdk-17.0.2\bin\java.exe" -javaagent:ServerWrapper.jar -Dserverwrapper.agentproxy=foxlaunch.legacy.JarLoader -cp ServerWrapper.jar;CatServer-1.16.5.jar pro.gravit.launcher.server.ServerWrapper
GravitLauncher (fork sashok724's Launcher) ServerWrapper v5.2.8-1 stable (build #1)
License for ServerWrapper GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022.08.02 12:18:24 [INFO] ServerWrapper: LaunchServer address: ws://localhost:9274/api. Title: Goldenbaton
2022.08.02 12:18:24 [INFO] Minecraft Version (for profile): 1.16.5
2022.08.02 12:18:24 [INFO] Start Minecraft Server
Loading libraries, please wait...
[12:18:24] [main/INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.35, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[12:18:24] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17.0.2 by Oracle Corporation
[12:18:25] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[12:18:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/danil/Desktop/testserver/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[12:18:25] [main/INFO]: Launching target 'fmlserver' with arguments [--gameDir, .]
[12:18:30] [modloading-worker-0/INFO]: Forge mod loading, version 36.2.35, for MC 1.16.5 with MCP 20210115.111550
[12:18:30] [modloading-worker-0/INFO]: MinecraftForge v36.2.35 Initialized
[12:18:32] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:18:33] [main/INFO]: Reloading ResourceManager: Default, forge-1.16.5-36.2.35-universal.jar, bukkit
[12:18:34] [Worker-Main-9/INFO]: Loaded 927 advancements
[12:18:35] [Server thread/INFO]: Starting minecraft server version 1.16.5
[12:18:35] [Server thread/INFO]: Loading properties
[12:18:35] [Server thread/INFO]: Default game type: SURVIVAL
[12:18:35] [Server thread/INFO]: Generating keypair
[12:18:35] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:18:35] [Server thread/INFO]: Using default channel type
[12:18:36] [Server thread/INFO]: This server is running CatServer version 1.16.5-caa59bdd (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
[12:18:36] [Server thread/INFO]: Debug logging is enabled
[12:18:36] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:18:36] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:18:37] [Server thread/INFO]: Preparing level "world"
[12:18:37] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:18:37] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:18:39] [Server thread/INFO]: Preparing spawn area: 0%
[12:18:39] [Server thread/INFO]: Preparing spawn area: 16%
[12:18:43] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[12:18:45] [Worker-Main-9/INFO]: Preparing spawn area: 87%
[12:18:46] [Server thread/INFO]: Time elapsed: 8421 ms
[12:18:46] [Server thread/INFO]: Done (8.788s)! For help, type "help"
[12:19:44] [User Authenticator #1/INFO]: Disconnecting /127.0.0.1:58971: Failed to verify username!
[12:19:44] [User Authenticator #1/ERROR]: Username 'Goodlol' tried to join with an invalid session
[12:19:44] [Server thread/INFO]: /127.0.0.1:58971 lost connection: Failed to verify username!

**Comment by SqdGoodlol** [comment]
GravitLauncher (fork sashok724's Launcher) ServerWrapper v5.2.8-1 stable (build #1)
License for ServerWrapper GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022.08.02 12:27:55 [INFO] ServerWrapper: LaunchServer address: ws://localhost:9274/api. Title: Goldenbaton
2022.08.02 12:27:55 [INFO] Minecraft Version (for profile): 1.16.5
2022.08.02 12:27:55 [INFO] Start Minecraft Server
Loading libraries, please wait...
[12:27:56] [main/INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.35, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[12:27:56] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17.0.2 by Oracle Corporation
[12:27:56] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[12:27:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/danil/Desktop/testserver/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[12:27:57] [main/INFO]: Launching target 'fmlserver' with arguments [--gameDir, .]
[12:28:01] [modloading-worker-0/INFO]: Forge mod loading, version 36.2.35, for MC 1.16.5 with MCP 20210115.111550
[12:28:01] [modloading-worker-0/INFO]: MinecraftForge v36.2.35 Initialized
[12:28:03] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:28:04] [main/INFO]: Reloading ResourceManager: Default, forge-1.16.5-36.2.35-universal.jar, bukkit
[12:28:05] [Worker-Main-12/INFO]: Loaded 927 advancements
[12:28:06] [Server thread/INFO]: Starting minecraft server version 1.16.5
[12:28:06] [Server thread/INFO]: Loading properties
[12:28:06] [Server thread/INFO]: Default game type: SURVIVAL
[12:28:06] [Server thread/INFO]: Generating keypair
[12:28:06] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:28:06] [Server thread/INFO]: Using default channel type
[12:28:07] [Server thread/INFO]: This server is running CatServer version 1.16.5-caa59bdd (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
[12:28:07] [Server thread/INFO]: Debug logging is enabled
[12:28:07] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:28:07] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:28:08] [Server thread/INFO]: Preparing level "world"
[12:28:08] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:28:08] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:28:10] [Server thread/INFO]: Preparing spawn area: 0%
[12:28:10] [Server thread/INFO]: Preparing spawn area: 53%
[12:28:14] [Worker-Main-12/INFO]: Preparing spawn area: 83%
[12:28:16] [Server thread/INFO]: Preparing spawn area: 84%
[12:28:17] [Server thread/INFO]: Preparing spawn area: 91%
[12:28:17] [Server thread/INFO]: Time elapsed: 8790 ms
[12:28:17] [Server thread/INFO]: Done (9.155s)! For help, type "help"
[12:29:36] [User Authenticator #1/INFO]: Disconnecting /127.0.0.1:59200: Failed to verify username!
[12:29:36] [User Authenticator #1/ERROR]: Username 'Goodlol' tried to join with an invalid session
[12:29:36] [Server thread/INFO]: /127.0.0.1:59200 lost connection: Failed to verify username!

**Comment by XionioXMaster** [comment]
Явно что-то с соединением, обратись к офф. Дискорд каналу гравита за помощью, у меня последняя версия CatServer работает как нужно.

**Comment by XionioXMaster** [comment]
> { "address": "ws://localhost:9274/api", "serverName": "Goldenbaton", "autoloadLibraries": false, "classpath": [], "classLoaderConfig": "SYSTEM_ARGS", "mainclass": "catserver.server.CatServerLaunch", "args": [], "oauthExpireTime": 0, "extendedTokens": { "checkServer": "_token_" }, "env": "STD" }


"serverName": "Goldenbaton",
Укажи профильное имя

**Comment by Kotori0629** [comment]
Work normally

**Comment by XionioXMaster** [comment]
> { "address": "ws://localhost:9274/api", "serverName": "Goldenbaton", "autoloadLibraries": false, "classpath": [], "classLoaderConfig": "SYSTEM_ARGS", "mainclass": "catserver.server.CatServerLaunch", "args": [], "oauthExpireTime": 0, "extendedTokens": { "checkServer": "_token_" }, "env": "STD" }

Не подключён токен
