### ISSUE TITLE
伪装插件加载错误

### ISSUE THREAD

**Issue by olcxian** [Luohuayu/CatServer#54]
[01:40:10] [Server thread/ERROR] [Minecraft]: Error occurred while enabling LibsDisguises v9.8.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:48) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServerAsync-1.12.2-76aa211]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServerAsync-1.12.2-76aa211]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServerAsync-1.12.2-76aa211]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436) [CraftServer.class:git-CatServerAsync-1.12.2-76aa211]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServerAsync-1.12.2-76aa211]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:388) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:328) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.CAT
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.entity.EntityType.valueOf(EntityType.java:20) ~[EntityType.class:git-CatServerAsync-1.12.2-76aa211]
	at me.libraryaddict.disguise.disguisetypes.DisguiseType.<init>(DisguiseType.java:256) ~[?:?]
	at me.libraryaddict.disguise.disguisetypes.DisguiseType.<clinit>(DisguiseType.java:21) ~[?:?]
	... 11 more

**Comment by Luohuayu** [comment]
不支持该插件
