### ISSUE TITLE
[1.12.2] MiraiMC无法正常登入

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [Luohuayu/CatServer#545]
**运行环境**
Minecraft版本: Forge 1.12.2
构建版本(从/version指令获取):
This server is running CatServer version git-CatServer-1.12.2-d4bc4dcc (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
相关模组/插件: MiraiMC

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)

```
#自动登入进行登入
[22:21:16] [Craft Scheduler Thread - 6/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] [AutoLogin] Auto login bot account: 3325669xxx Protocol: IPAD
[22:21:16] [Craft Scheduler Thread - 6/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] 登录新的机器人账号: 3325669xxx, 协议: IPAD
[22:21:17] [Craft Scheduler Thread - 6/WARN] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] Plugin MiraiMC v1.7 generated an exception while executing task 14
java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)
	at net.mamoe.mirai.utils.PlatformLogger$1.<init>(PlatformLogger.jvm.kt) ~[?:?]
	at net.mamoe.mirai.utils.PlatformLogger$1.<clinit>(PlatformLogger.jvm.kt) ~[?:?]
	at net.mamoe.mirai.utils.PlatformLogger.<init>(PlatformLogger.jvm.kt:56) ~[?:?]
	at net.mamoe.mirai.utils.DefaultFactory.create(MiraiLogger.kt:568) ~[?:?]
	at net.mamoe.mirai.utils.MiraiLogger$Factory.create(MiraiLogger.kt:64) ~[?:?]
	at net.mamoe.mirai.utils.MiraiLogger$Factory.create(MiraiLogger.kt:79) ~[?:?]
	at net.mamoe.mirai.utils.MiraiLogger$Factory$INSTANCE.create(MiraiLogger.kt) ~[?:?]
	at net.mamoe.mirai.utils.WindowHelperJvm.<clinit>(SwingSolver.kt:135) ~[?:?]
	at net.mamoe.mirai.utils.LoginSolver.<clinit>(LoginSolver.jvm.kt:92) ~[?:?]
	at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:241) ~[?:?]
	at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:630) ~[?:?]
	at me.dreamvoid.miraimc.api.MiraiBot.login(MiraiBot.java:330) ~[?:?]
	at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:128) ~[?:?]
	at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:169) ~[?:?]
	at me.dreamvoid.miraimc.bukkit.MiraiAutoLogin.lambda$doStartUpAutoLogin$0(MiraiAutoLogin.java:83) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-d4bc4dcc]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-d4bc4dcc]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_341]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
[22:21:17] [Server thread/INFO] [coroutil]: CoroUtil being reinitialized

#手动执行登入
[22:23:34] [Craft Scheduler Thread - 34/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] 登录新的机器人账号: 3325669xxx, 协议: ANDROID_PHONE
[22:23:34] [Craft Scheduler Thread - 34/WARN] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] Plugin MiraiMC v1.7 generated an exception while executing task 46
java.lang.NoClassDefFoundError: Could not initialize class me.dreamvoid.miraimc.api.MiraiBot$1
	at me.dreamvoid.miraimc.api.MiraiBot.login(MiraiBot.java:330) ~[?:?]
	at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:128) ~[?:?]
	at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:169) ~[?:?]
	at me.dreamvoid.miraimc.bukkit.commands.MiraiCommand$1.run(MiraiCommand.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-d4bc4dcc]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-d4bc4dcc]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_341]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]


#关服
Error occurred while disabling MiraiMC v1.7 (Is it up to date?)
java.lang.NoClassDefFoundError: net.mamoe.mirai.utils.LoginSolver
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:170) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[JavaPlugin.class:git-CatServer-1.12.2-d4bc4dcc]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:352) [JavaPluginLoader.class:git-CatServer-1.12.2-d4bc4dcc]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [SimplePluginManager.class:git-CatServer-1.12.2-d4bc4dcc]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [SimplePluginManager.class:git-CatServer-1.12.2-d4bc4dcc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:405) [CraftServer.class:git-CatServer-1.12.2-d4bc4dcc]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:525) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:743) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
```

**导致的问题:**
MiraiMC无法正常登入

**复现方法**
设置完自动登后开服
执行指令/Mirai login <qq> <密码>后
关服

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
使用MiraiMC最新版未复现, 请使用最新版, 如果依然无法使用请新开Issues并上传插件

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱

**Comment by Kotori0629** [comment]
尝试移除plugins/MiraiMC重新生成, 测试环境和你使用的相同为MiraiMC v1.7 , 在CatServer 1.12.2/CatServer1.16.5工作正常

![F%NWCQY3$TP)YW8878)9857](https://user-images.githubusercontent.com/81866089/192240008-5443fa21-c74c-4064-b3ff-e0322594cd10.png)
![20220926171841](https://user-images.githubusercontent.com/81866089/192240227-4e02f590-5a6f-4501-ab68-d6a3b89cf8f2.png)
![image](https://user-images.githubusercontent.com/81866089/192240422-727f5e5a-39bf-4c1b-88eb-d509ce31edc7.png)
![image](https://user-images.githubusercontent.com/81866089/192240522-607521c1-36a8-41d2-b021-969eb7d30170.png)
