### ISSUE TITLE
无法正常使用 VexView

### ISSUE THREAD

**Issue by LDS-XiaoYe** [Luohuayu/CatServer#56]
catserver 最新版本
vexview最新版本
[VexView] Plugin VexView v2.5 generated an exception while executing task 53
java.lang.NullPointerException: null
        at lk.vexview.scoreboard.?h.?(z:225) ~[?:?]
        at lk.vexview.scoreboard.?h.enum(z:60) ~[?:?]
        at lk.vexview.scoreboard.?h$?B.run(z:23) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServerAsync-1.12.2-76aa211]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServerAsync-1.12.2-76aa211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by Luohuayu** [comment]
插件问题请反馈给插件作者
