### ISSUE TITLE
[1.12.2] spark插件无法正确加载

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#562]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): CatServer-8d58cdb8
相关模组/插件: 
ATM3 6.1.1整合包
EssentialsX-2.19.6
LuckPerms-Bukkit-5.4.40
spark-1.9.33-bukkit(1.8.19也一样)

**导致的问题r**
```
[08:23:32] [Server thread/ERROR]: Error occurred while enabling spark v1.8.19 (Is it up to date?)
java.lang.NoSuchFieldError: LOCALE
        at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudience.contributePointers(BukkitAudience.java:115) ~[?:?]
        at me.lucko.spark.lib.adventure.platform.facet.FacetAudience.pointers(FacetAudience.java:449) ~[?:?]
        at me.lucko.spark.lib.adventure.pointer.Pointered.getOrDefault(Pointered.java:65) ~[Pointered.class:?]
        at me.lucko.spark.lib.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:114) ~[?:?]
        at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:100) ~[?:?]
        at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:174) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1128) ~[?:1.8.0_312]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2674) ~[?:1.8.0_312]
        at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:174) ~[?:?]
        at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
        at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
        at me.lucko.spark.bukkit.BukkitSparkPlugin.onEnable(BukkitSparkPlugin.java:59) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-8d58cdb8]
        at catserver.server.command.internal.CommandPlugin.loadPlugin(CommandPlugin.java:123) [CommandPlugin.class:git-CatServer-1.12.2-8d58cdb8]
        at catserver.server.command.internal.CommandPlugin.execute(CommandPlugin.java:46) [CommandPlugin.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [SimpleCommandMap.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:712) [CraftServer.class:git-CatServer-1.12.2-8d58cdb8]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1667) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1468) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

**复现方法**
安装ATM3整合包和spark插件

**Comment by Luohuayu** [comment]
配置文件关闭plugin.defaultInstall.spark选项 更换spark forge版
