### ISSUE TITLE
自定义NPC脚本调用Vec3d类报错

### ISSUE THREAD

**Issue by ChloePrime** [Luohuayu/CatServer#58]
我写了一个自定义NPC脚本，调用了原版MC中Vec3d类的字段，但右键脚本道具执行该脚本时会报错。
单机环境下无该问题。
下面是一段会触发报错的NPC脚本

> function toJsVec3d(mcVec3d) {
    //下面三个SRG名称分别代表Vec3d类的x，y，z
    return {
        x : mcVec3d.field_72450_a,
        y : mcVec3d.field_72448_b,
        z : mcVec3d.field_72449_c
    };
}
function interact(e) {
    //下面的SRG名称函数表示获取玩家视线向量，返回类型为原版的Vec3d
    var vec = toJsVec3d(e.player.getMCEntity().func_70040_Z());
}

原始脚本报错内容：
`Sun Dec 29 18:12:01 CST 2019 tab 1:
java.lang.NoClassDefFoundError: net/minecraft/util/math/Vec2f
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at jdk.internal.dynalink.beans.AccessibleMembersLookup.lookupAccessibleMembers(AccessibleMembersLookup.java:213)
	at jdk.internal.dynalink.beans.AccessibleMembersLookup.<init>(AccessibleMembersLookup.java:119)
	at jdk.internal.dynalink.beans.FacetIntrospector.<init>(FacetIntrospector.java:113)
	at jdk.internal.dynalink.beans.BeanIntrospector.<init>(BeanIntrospector.java:92)
	at jdk.internal.dynalink.beans.BeanLinker.createFacetIntrospector(BeanLinker.java:128)
	at jdk.internal.dynalink.beans.AbstractJavaLinker.<init>(AbstractJavaLinker.java:135)
	at jdk.internal.dynalink.beans.BeanLinker.<init>(BeanLinker.java:110)
	at jdk.internal.dynalink.beans.BeansLinker$1.computeValue(BeansLinker.java:139)
	at jdk.internal.dynalink.beans.BeansLinker$1.computeValue(BeansLinker.java:132)
	at java.lang.ClassValue.getFromHashMap(Unknown Source)
	at java.lang.ClassValue.getFromBackup(Unknown Source)
	at java.lang.ClassValue.get(Unknown Source)
	at jdk.internal.dynalink.beans.BeansLinker.getLinkerForClass(BeansLinker.java:158)
	at jdk.internal.dynalink.beans.BeansLinker.getGuardedInvocation(BeansLinker.java:272)
	at jdk.nashorn.internal.runtime.linker.NashornBeansLinker.getGuardedInvocation(NashornBeansLinker.java:137)
	at jdk.nashorn.internal.runtime.linker.NashornBeansLinker.getGuardedInvocation(NashornBeansLinker.java:124)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$3082$28A$\^eval\_.toJsVec3d(<eval>:2)
	at jdk.nashorn.internal.scripts.Script$Recompilation$3081$147A$\^eval\_.interact(<eval>:7)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at noppes.npcs.controllers.ScriptContainer.run(ScriptContainer.java:169)
	at noppes.npcs.controllers.ScriptContainer.run(ScriptContainer.java:126)
	at noppes.npcs.api.wrapper.ItemScriptedWrapper.runScript(ItemScriptedWrapper.java:149)
	at noppes.npcs.EventHooks.onScriptItemInteract(EventHooks.java:528)
	at noppes.npcs.ScriptPlayerEventHandler.invoke(ScriptPlayerEventHandler.java:177)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_241_ScriptPlayerEventHandler_invoke_RightClickItem.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187)
	at net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:1195)
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:426)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:1189)
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(Util.java:50)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.math.Vec2f
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 53 more
`

报错原因疑似CatServer/patches/net/minecraft/util/math/Vec3d.java.patch该文件中出现了Vec2f但是没有import。

**Comment by Luohuayu** [comment]
Vec2f为SideOnly(Side.CLIENT) 只能客户端调用

**Comment by Luohuayu** [comment]
已测试Forge官服存在同样问题, 建议向Forge反馈
