### ISSUE TITLE
error with CraftTask.java:76

### ISSUE THREAD

**Issue by DruidIdrur** [Luohuayu/CatServer#61]
> [14:20:54] [Craft Scheduler Thread - 373/WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v2.2.5 generated an exception while executing task 13
java.lang.NullPointerException: null
at com.iridium.iridiumskyblock.IridiumSkyblock.addPages(IridiumSkyblock.java:264) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-039e205]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-039e205]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]

Server Version: CatServer-1.12.2-039e205

**Comment by Luohuayu** [comment]
Report it to plugin author
