### ISSUE TITLE
[1.12.2] 希望大佬可以让猫端兼容一下粘液世界SlimeWorldManager方便做副本

### ISSUE THREAD

**Issue by nuyanfire** [Luohuayu/CatServer#620]
【一、插件用途-用于独立副本制作】
该插件主要是配合mcbbs论坛上的副本插件Csg-Plus制作独立的副本。是一个管理世界的插件非常好用。
【二、用cat端使用该插件遇到的问题】
①
粘液世界这个插件，分为前置和主体。前置的启动主要放在启动脚本里面。
②
不兼容的就是最新版的前置[slimeworldmanager-classmodifier-2.2.1.jar](https://github.com/Grinderwolf/Slime-World-Manager/releases/download/2.2.1/slimeworldmanager-classmodifier-2.2.1.jar)
③
而副本插件Csg-Plus 如果想使用独立世界，就要用到粘液世界的最新版本。
④
粘液世界前置代码量不多，很少。
【三、粘液世界的连接】
连接：
论坛搬运贴（需解锁卡查看）：https://www.mcbbs.net/forum.php?mod=viewthread&tid=909354
粘液世界spigotmc帖子连接： https://www.spigotmc.org/resources/slimeworldmanager.69974/
粘液世界github连接： https://github.com/Grinderwolf/Slime-World-Manager/releases
粘液世界插件安装教程： https://github.com/Grinderwolf/Slime-World-Manager/blob/develop/.docs/usage/install.md

**Comment by Kotori0629** [comment]
提供错误报告

**Comment by nuyanfire** [comment]
[14:07:15] [Server thread/INFO]: Injecting itemstacks
[14:07:15] [Server thread/INFO]: Itemstack injection complete
[14:07:15] [Server thread/INFO]: Loading properties
[14:07:15] [Server thread/INFO]: Default game type: SURVIVAL
[14:07:15] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: ain
        at net.minecraft.server.management.PlayerList.initCraftServer(PlayerList.java:136) ~[pl.class:?]
        at net.minecraft.server.MinecraftServer.func_184105_a(MinecraftServer.java:1463) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:229) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:853) [?:1.8.0_292]
[14:07:15] [Server thread/ERROR]: This crash report has been saved to: E:\服务器\.\crash-reports\crash-2022-07-24_14.07.15-server.txt
[14:07:15] [Server thread/INFO]: Stopping server
[14:07:15] [Server thread/INFO]: Saving worlds
[14:07:15] [Server thread/INFO]: The state engine was in incorrect state POSTINITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded.
10秒后重启服务器,如需关闭服务器请直接关闭该窗口

**Comment by nuyanfire** [comment]
org/bukkit/craftbukkit/v1_12_R1/CraftServer:
  - addWorld(org.bukkit.World)@v1_12_R1/CraftServer_addWorld.txt
  
  
  
粘液世界的前置 里面代码量很少。 主要是以下的几个文件 v1_12_R1 
我排查的时候 可能是下面这个文件里面出现问题。
org/bukkit/craftbukkit/v1_12_R1/CraftServer:
  - addWorld(org.bukkit.World)@v1_12_R1/CraftServer_addWorld.txt
  ----------------------------------------------------------------------
粘液世界前置，其他有逻辑代码的部分：
grinderwolf.swm.clsm下的三个文件

**Comment by Luohuayu** [comment]
前置插件ASM修改服务端代码, 而且是以Spigot为基础做修改, Forge混合端无法兼容
