### ISSUE TITLE
[1.12.2] 高级火箭发射空间站NPE

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#663]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.12.2
构建版本(从/version指令获取):  CatServer-1.12.2-dae70adc
相关模组/插件:  E2E整合包(1.86)

**描述这个BUG**
```
Time: 12/4/22 9:08 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.world.World.handler$zzf000$checkLightFor(World.java:4463)
	at net.minecraft.world.World.func_180500_c(World.java)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingHooks.scheduleRelightChecksForColumn(LightingHooks.java:86)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingHooks.relightSkylightColumn(LightingHooks.java:36)
	at net.minecraft.world.chunk.Chunk.func_76615_h(Chunk.java:2017)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:699)
	at zmaster587.advancedRocketry.util.StorageChunk.readFromNBT(StorageChunk.java:371)
	at zmaster587.advancedRocketry.item.ItemPackedStructure.getStructure(ItemPackedStructure.java:36)
	at zmaster587.advancedRocketry.entity.EntityRocket.unpackSatellites(EntityRocket.java:1557)
	at zmaster587.advancedRocketry.entity.EntityRocket.reachSpaceUnmanned(EntityRocket.java:1355)
	at zmaster587.advancedRocketry.entity.EntityRocket.onOrbitReached(EntityRocket.java:1303)
	at zmaster587.advancedRocketry.entity.EntityRocket.func_70071_h_(EntityRocket.java:1183)
	at net.minecraft.world.World.func_72866_a(World.java:2307)
	at net.minecraft.world.World.func_72870_g(World.java:2261)
	at net.minecraft.world.World.func_72939_s(World.java:2031)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.handler$zzf000$checkLightFor(World.java:4463)
	at net.minecraft.world.World.func_180500_c(World.java)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingHooks.scheduleRelightChecksForColumn(LightingHooks.java:86)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingHooks.relightSkylightColumn(LightingHooks.java:36)
	at net.minecraft.world.chunk.Chunk.func_76615_h(Chunk.java:2017)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:699)
	at zmaster587.advancedRocketry.util.StorageChunk.readFromNBT(StorageChunk.java:371)
	at zmaster587.advancedRocketry.item.ItemPackedStructure.getStructure(ItemPackedStructure.java:36)
	at zmaster587.advancedRocketry.entity.EntityRocket.unpackSatellites(EntityRocket.java:1557)
	at zmaster587.advancedRocketry.entity.EntityRocket.reachSpaceUnmanned(EntityRocket.java:1355)
	at zmaster587.advancedRocketry.entity.EntityRocket.onOrbitReached(EntityRocket.java:1303)
	at zmaster587.advancedRocketry.entity.EntityRocket.func_70071_h_(EntityRocket.java:1183)
	at net.minecraft.world.World.func_72866_a(World.java:2307)
	at net.minecraft.world.World.func_72870_g(World.java:2261)

-- Entity being ticked --
Details:
	Entity Type: advancedrocketry:rocket (zmaster587.advancedRocketry.entity.EntityRocket)
	Entity ID: 37863672
	Entity Name: Rocket
	Entity's Exact location: 1679.50, 1001.27, -494.50
	Entity's Block location: World: (1679,1001,-495), Chunk: (at 15,62,1 in 104,-31; contains blocks 1664,0,-496 to 1679,255,-481), Region: (3,-1; contains chunks 96,-32 to 127,-1, blocks 1536,0,-512 to 2047,255,-1)
	Entity's Momentum: 0.00, 1.34, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2031)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742)
```

**复现方法**

发射空间站就崩了

**Comment by Coloryr** [comment]
重启服务器也会崩
一样的报错

**Comment by Coloryr** [comment]
删除phosphor后正常

**Comment by Luohuayu** [comment]
phosphor使用asm修改代码导致其他MOD光照处理错误
