### ISSUE TITLE
[1.16.5] 服务器每次启动都会报错

### ISSUE THREAD

**Issue by Rwagsu** [Luohuayu/CatServer#680]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 根本无法打开服务器，所以我也不知道构建版本
相关模组/插件: 没有

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
`D:\SFolder\documents\Minecraft\Minecraft Server\Java\Is using\CatServer>java -Xms6G -Xmx10G -jar CatServer-1.16.5-da9654d4-server.jar
Loading libraries, please wait...
[19:58:29] [main/INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.39, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[19:58:29] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_351 by Oracle Corporation
[19:58:30] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[19:58:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/SFolder/documents/Minecraft/Minecraft%20Server/Java/Is%20using/CatServer/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
Exception in thread "main" [19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.reflect.InvocationTargetException
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.lang.reflect.Method.invoke(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at foxlaunch.FoxServerLauncher.main(FoxServerLauncher.java:33)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at catserver.server.CatServerLaunch.main(CatServerLaunch.java:8)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.nio.file.ProviderNotFoundException: Provider not found
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.nio.file.FileSystems.newFileSystem(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer$MinecraftLocator.<init>(ModDiscoverer.java:154)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.<init>(ModDiscoverer.java:93)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:215)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:107)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:114)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.util.stream.ReferencePipeline.collect(Unknown Source)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[19:58:30] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:   ... 6 more

D:\SFolder\documents\Minecraft\Minecraft Server\Java\Is using\CatServer>Pause
请按任意键继续. . .`
**导致的问题r**
服务器无法启动
**复现方法**
我也不知道如何复现，大概是下载服务器后使用“java -Xms6G -Xmx10G -jar CatServer-1.16.5-da9654d4-server.jar”来启动，或者开服中途强行关掉几次服务器（应该不是，我有把所有文件都删除一遍再开服，但是还没用）或者是Java原因（直接点击服务器文件生成的文件要比使用命令生成的多，但是我检查过，jar默认打开方式是和命令行里的Java版本一模一样，或许是配置原因？但是我的配置没有缺少啊？）
**截图/视频**
(如果没有可以忽略)

**Comment by Rwagsu** [comment]
emmm......这个好像是Forge的问题，因为我换成原版Forge用相同版本也会报错......

**Comment by Kotori0629** [comment]
建议用pastebin粘贴错误报告后重新发
