### ISSUE TITLE
[1.12.2] bukkit多世界与forge chunk ticket功能的兼容性问题

### ISSUE THREAD

**Issue by MrMks** [Luohuayu/CatServer#704]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): 222f2a5f，理论any
相关模组/插件: 
Multiverse-Core 2.5.0
Dynmap-3.4-forge-1.12.2

**描述这个BUG**

```text
java.lang.NullPointerException
    at com.google.common.collect.LinkedHashMultimap.create(LinkedHashMultimap.java:122)
    at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:860)
    at net.minecraftforge.common.ForgeChunkManager.releaseTicket(ForgeChunkManager.java:780)
    at org.dynmap.forge_1_12_2.DynmapPlugin.doIdleOutOfWorlds(DynmapPlugin.java:386)
    at org.dynmap.forge_1_12_2.DynmapPlugin.access$2300(DynmapPlugin.java:120)
    at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:1001)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_506_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:268)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:890)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:853)
```

https://github.com/Luohuayu/CatServer/blob/222f2a5f4aefeb8f54bac10b5090d868418f0b0d/src/main/java/net/minecraftforge/common/ForgeChunkManager.java#L860

自bukkit侧卸载世界不会经过forge侧的forced chunk相关机制的检查(ForgeChunkManager)，使得世界直接被卸载，自后当mod释放对应世界的ticket便会导致自null创建copy，产生npe，使得服务端崩溃。

此现象理论不限于上述所列mod/plugin触发。

此外，这一行为分别自plugin侧或自mod侧出发应均为预期行为（plugin侧预期世界被立即卸载，mod侧预期在释放ticket前世界不会被卸载）。

**复现方法**
安装所列模组/插件后开服，使用mv创建新世界后重启服务器，确认新世界被dynmap所渲染，后，使用mv卸载这一世界，等待30s左右。

**截图/视频**
(如果没有可以忽略)

**Comment by Lonelyxiya** [comment]
抱歉提及错了:(
