### ISSUE TITLE
[1.12.2] spark 插件版無法啟用/使用

### ISSUE THREAD

**Issue by leonpano2006** [Luohuayu/CatServer#755]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): This server is running CatServer version git-CatServer-1.12.2-fed56812 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
相关模组/插件: spark

**描述这个BUG**
```
[18:33:00] [Server thread/ERROR] [net.minecraft.network.NetHandlerPlayServer]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'spark' in plugin spark v1.10.38
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-fed56812]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-fed56812]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:712) ~[CraftServer.class:git-CatServer-1.12.2-fed56812]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1669) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1470) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_362]
	at net.minecraft.util.Util.func_181617_a(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:904) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
Caused by: java.lang.NullPointerException
	at me.lucko.spark.bukkit.BukkitSparkPlugin.onCommand(BukkitSparkPlugin.java:111) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-fed56812]
	... 15 more```
[debug.log](https://github.com/Luohuayu/CatServer/files/11472427/debug.log)


**导致的问题r**
插件無法使用

**复现方法**
安裝最新版spark bukkit
伺服器端或者是客戶端輸入`/spark`

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
CatServer已内置Spark，无需额外添加

**Comment by leonpano2006** [comment]
我想用它最新版的功能當你那個不是最新版
