### ISSUE TITLE
关服时无法正常关闭

### ISSUE THREAD

**Issue by starxjys** [Luohuayu/CatServer#77]
[19:36:36] [Server thread/INFO] [FML]: Unloading dimension 6
[19:36:36] [Server thread/INFO] [Actually Additions]: Unloaded WorldData!
[19:36:36] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: 0
[19:36:36] [Server thread/WARN] []: Exception in thread "Server thread" 
[19:36:36] [Server thread/WARN] []: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Core (galacticraftcore)
[19:36:36] [Server thread/WARN] []: Caused by: java.lang.IllegalArgumentException: Failed to unregister dimension for id 0; No provider registered
[19:36:36] [Server thread/WARN] []: 	at net.minecraftforge.common.DimensionManager.unregisterDimension(DimensionManager.java:170)
[19:36:36] [Server thread/WARN] []: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.unregisterPlanets(WorldUtil.java:619)
[19:36:36] [Server thread/WARN] []: 	at micdoodle8.mods.galacticraft.core.GalacticraftCore.onServerStop(GalacticraftCore.java:562)
[19:36:36] [Server thread/WARN] []: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:36:36] [Server thread/WARN] []: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:36:36] [Server thread/WARN] []: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:36:36] [Server thread/WARN] []: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:36:36] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:636)
[19:36:36] [Server thread/WARN] []: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[19:36:36] [Server thread/WARN] []: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:36:36] [Server thread/WARN] []: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:36:36] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[19:36:36] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[19:36:36] [Server thread/WARN] []: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:36:36] [Server thread/WARN] []: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:36:36] [Server thread/WARN] []: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:36:36] [Server thread/WARN] []: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:36:36] [Server thread/WARN] []: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:36:36] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[19:36:36] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:852)
[19:36:36] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:511)
[19:36:36] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
[19:36:36] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)
[19:37:34] [Spigot Watchdog Thread/ERROR] [Minecraft]: The server has stopped responding!
[19:37:34] [Spigot Watchdog Thread/ERROR] [Minecraft]: Please report this to http://www.spigotmc.org/
[19:37:34] [Spigot Watchdog Thread/ERROR] [Minecraft]: Be sure to include ALL relevant console errors and Minecraft crash reports
[19:37:34] [Spigot Watchdog Thread/ERROR] [Minecraft]: Spigot version: git-CatServerAsync-1.12.2-be9c40a (MC: 1.12.2)
[19:37:34] [Spigot Watchdog Thread/ERROR] [Minecraft]: ------------------------------
[19:37:34] [Spigot Watchdog Thread/ERROR] [Minecraft]: Server thread dump (Look for plugins here before reporting to Spigot!):
[19:37:34] [Spigot Watchdog Thread/ERROR] [Minecraft]: ------------------------------
[19:37:34] [Spigot Watchdog Thread/WARN] []: Exception in thread "Spigot Watchdog Thread" 
[19:37:34] [Spigot Watchdog Thread/WARN] []: java.lang.NullPointerException
[19:37:34] [Spigot Watchdog Thread/WARN] []: 	at org.spigotmc.WatchdogThread.dumpThread(WatchdogThread.java:107)
[19:37:34] [Spigot Watchdog Thread/WARN] []: 	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:74)
`

**Comment by Iltotore** [comment]
You have an error in Galacticraft Core:
```
Caused by: java.lang.IllegalArgumentException: Failed to unregister dimension for id 0; No provider registered
```
There is an issue with one of your dimensions.
It doesn't seem to be a CatServer issue. Try posting your problem in Mods/Galacticraft forums/support

**Comment by starxjys** [comment]
好的，谢谢
