### ISSUE TITLE
[1.18.2] IllegalStateException: Try to modify unload queue when unloading chunks

### ISSUE THREAD

**Issue by NattoCB** [Luohuayu/CatServer#808]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.18.2
构建版本(从/version指令获取):  6c3f596 当前最新release

**导致的问题**

这个问题导致了服务器 watchdog 宕机，但没有 crash-report，目前只能提供日志来帮助分析

宕机之后并不会导致服务器关闭，而是一直卡住，所有玩家并没有被主动踢出

**复现方法**

偶然遇见，难以复现，但测试期间三周出现了四次

**描述这个BUG**

完整日志
https://pastebin.com/vkdBrD4z

主要部分和主线程dump
```java
[17:43:16] [Worker-Main-1015/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: minecraft:
[17:43:16] [Worker-Main-1015/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: minecraft:
[17:43:16] [Worker-Main-1015/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: minecraft:
[17:48:55] [Worker-Main-1821/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: minecraft:
[17:49:41] [Server thread/INFO] []: java.lang.IllegalStateException: Try to modify unload queue when unloading chunks!
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157527_(PersistentEntitySectionManager.java:168)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157524_(PersistentEntitySectionManager.java:161)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.m_143075_(ChunkMap.java:1251)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkHolder.m_200425_(ChunkHolder.java:348)
[17:49:41] [Server thread/INFO] []: 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
[17:49:41] [Server thread/INFO] []: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:595)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:605)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:300)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1056)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1045)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:1030)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:956)
[17:49:41] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:312)
[17:49:41] [Server thread/INFO] []: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:51:05] [Worker-Main-1014/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: minecraft:
[17:51:05] [Worker-Main-1014/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: minecraft:
[17:51:17] [Server thread/WARN] [net.minecraft.server.network.ServerGamePacketListenerImpl]: XueShang moved wrongly!
[17:51:18] [Server thread/INFO] []: java.lang.IllegalStateException: Try to modify unload queue when unloading chunks!
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157527_(PersistentEntitySectionManager.java:168)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157524_(PersistentEntitySectionManager.java:161)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.m_143075_(ChunkMap.java:1251)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkHolder.m_200425_(ChunkHolder.java:348)
[17:51:18] [Server thread/INFO] []: 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
[17:51:18] [Server thread/INFO] []: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:595)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:605)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:300)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1056)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1045)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:1030)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:956)
[17:51:18] [Server thread/INFO] []: 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:312)
[17:51:18] [Server thread/INFO] []: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:51:42] [Worker-Main-1014/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: kaisyn:village/meadow_swiss/villagers
[17:51:42] [Worker-Main-1014/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: kaisyn:village/meadow_swiss/villagers
[17:51:43] [Worker-Main-1014/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: kaisyn:village/meadow_swiss/villagers
[17:51:45] [Worker-Main-1014/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: kaisyn:village/meadow_swiss/villagers
[17:55:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Saving is already turned on
[17:55:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Saving the game (this may take a moment!)
[17:55:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Saved the game
[17:55:38] [Worker-Main-1015/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: minecraft:
[17:55:38] [Worker-Main-1015/WARN] [net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement]: Empty or non-existent pool: minecraft:
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: ------------------------------
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: The server has stopped responding! This is (probably) not a Spigot bug.
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: If you see a plugin in the Server thread dump below, then please report it to that author
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 	 *Especially* if it looks like HTTP or MySQL operations are occurring
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: If you see a world save or edit, then it means you did far more than your server can handle at once
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 	 If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: If you are unsure or still think this is a Spigot bug, please report to https://www.spigotmc.org/
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: Be sure to include ALL relevant console errors and Minecraft crash reports
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: Spigot version: 1.18.2-6c3f5965 (MC: 1.18.2)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: ------------------------------
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: Server thread dump (Look for plugins here before reporting to Spigot!):
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: ------------------------------
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: Current Thread: Server thread
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 	PID: 171 | Suspended: false | Native: false | State: TIMED_WAITING
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 	Stack:
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_5667_(BlockableEventLoop.java:152)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:142)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:154)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.m_6522_(Level.java:367)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:123)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.m_6325_(Level.java:362)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.m_46745_(Level.java:358)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.getBlockEntity(Level.java:801)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.m_7702_(Level.java:789)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/champions@1.18.2-2.1.6.3/top.theillusivec4.champions.common.util.ChampionHelper.nearActiveBeacon(ChampionHelper.java:82)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/champions@1.18.2-2.1.6.3/top.theillusivec4.champions.common.util.ChampionHelper.checkPotential(ChampionHelper.java:32)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/champions@1.18.2-2.1.6.3/top.theillusivec4.champions.common.util.ChampionBuilder.createRank(ChampionBuilder.java:110)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/champions@1.18.2-2.1.6.3/top.theillusivec4.champions.common.util.ChampionBuilder.spawn(ChampionBuilder.java:40)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/champions@1.18.2-2.1.6.3/top.theillusivec4.champions.common.ChampionEventsHandler.lambda$onLivingJoinWorld$7(ChampionEventsHandler.java:86)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/champions@1.18.2-2.1.6.3/top.theillusivec4.champions.common.ChampionEventsHandler$$Lambda$18521/0x00000008032ee9f0.accept(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/forge@40.2.4/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/champions@1.18.2-2.1.6.3/top.theillusivec4.champions.common.ChampionEventsHandler.onLivingJoinWorld(ChampionEventsHandler.java:81)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.eventbus.ASMEventHandler_688_ChampionEventsHandler_onLivingJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus$$Lambda$4425/0x000000080167f070.invoke(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:94)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$addWorldGenChunkEntities$2(PersistentEntitySectionManager.java:136)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager$$Lambda$23417/0x0000000803c2f928.accept(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.EntityType$1.m_147060_(EntityType.java:537)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.EntityType$1$$Lambda$18342/0x00000008032ae758.apply(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.Optional.map(Optional.java:260)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.EntityType.m_20645_(EntityType.java:515)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.EntityType$1.m_147056_(EntityType.java:536)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.EntityType$1$$Lambda$18341/0x00000008032ae528.accept(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:535)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157559_(PersistentEntitySectionManager.java:135)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_143327_(ServerLevel.java:1804)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.m_143064_(ChunkMap.java:636)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$28(ChunkMap.java:666)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap$$Lambda$21598/0x00000008039a9578.m_196866_(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:500)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$30(ChunkMap.java:674)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap$$Lambda$18301/0x00000008032a7cf0.apply(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either$$Lambda$16114/0x0000000802aa5d90.apply(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$31(ChunkMap.java:658)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap$$Lambda$18271/0x000000080329a500.apply(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkTaskPriorityQueueSorter$$Lambda$18201/0x0000000803288478.run(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:595)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:605)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:300)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1056)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1045)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:1031)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:956)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:312)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer$$Lambda$15892/0x00000008027a0690.run(Unknown Source)
[17:58:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
```

相关模组/插件:  
player-animation-lib-forge-1.0.2+1.18.jar
artifacts-1.18.2-4.2.2.jar
YungsApi-1.18.2-Forge-2.2.9.jar
champions-forge-1.18.2-2.1.6.3.jar
GrimoireOfGaia4-1.18.2-2.0.0-beta.2.jar
Rex's-AdditionalStructures-1.18.2-(v.3.1.1).jar
Steam_Rails-1.4.3+forge-mc1.18.2.jar
TravelersTitles-1.18.2-Forge-2.1.1.jar
createcafe-1.10.2-1.18.2.jar
curios-forge-1.18.2-5.0.9.1.jar
create-1.18.2-0.5.1.c.jar
createdeco-1.3.3-1.18.2.jar
Patchouli-1.18.2-71.1.jar
ars_nouveau-1.18.2-2.9.0.jar
locusazzurro_icaruswings-1.18.2-0.4.0.jar
Quark-3.2-358.jar
StorageDrawers-1.18.2-10.2.1.jar
irons_spellbooks-1.18.2-1.1.4.3.jar
EnigmaticLegacy-2.25.0.jar
worldedit-mod-7.2.10.jar
cfm-7.0.0-pre35-1.18.2.jar
alexsdelight-1.18.2-1.3.3.jar
alexsmobs-1.18.6.jar
FarmersDelight-1.18.2-1.2.2.jar
L_Enders+Cataclysm-0.51-changed+Them+-1.18.2.jar
lootr-1.18.2-0.3.25.63.jar
Aquaculture-1.18.2-2.3.12.jar
exoticbirds-1.18.2-1.8.0.jar

**Comment by Kotori0629** [comment]
这个也一样 再观察吧
