### ISSUE TITLE
[1.16.5] Catserver与citizens2中的path设置寻路点不兼容缺nms方法导致崩服。

### ISSUE THREAD

**Issue by skydalian** [Luohuayu/CatServer#880]
**运行环境**
JAVA11
Minecraft版本1.16.5: 

构建版本: 
69069a9c（MC:1.16.5） 1.16.5-R0.1-SNAPSHOT
相关模组/插件: 
citizens2插件
**描述这个BUG**
当用Citizens2插件创建一个npc后并且使用自带的路径点功能/npc path 创建路径点后会导致服务器崩溃
并显示报错:
16:10:16] [Server thread/ERROR]: Error occurred while disabling Citizens v2.0.33-SNAPSHOT (build 3316) (Is it up to date?)
 org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:453) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:181) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:172) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:131) ~[?:?]
        at net.citizensnpcs.trait.ScoreboardTrait.onDespawn(ScoreboardTrait.java:110) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:106) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPCRegistry.deregisterAll(CitizensNPCRegistry.java:115) ~[?:?]
        at net.citizensnpcs.trait.waypoint.EntityMarkers.destroyMarkers(EntityMarkers.java:54) ~[?:?]
        at net.citizensnpcs.trait.waypoint.LinearWaypointProvider$LinearWaypointEditor.end(LinearWaypointProvider.java:319) ~[?:?]
        at net.citizensnpcs.editor.Editor.leaveAll(Editor.java:55) ~[?:?]
        at net.citizensnpcs.Citizens.onDisable(Citizens.java:357) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:504) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:496) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:344) ~[?:1.16.5-1d8d6313]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:649) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:595) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:818) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[crash-2024-04-24_22.35.09-server.txt](https://github.com/Luohuayu/CatServer/files/15108009/crash-2024-04-24_22.35.09-server.txt)

**导致的问题r**
citizens2插件无法正常使用npc路径点功能。
**复现方法**
装上citizens2后输入/npc create xx后在输入/npc path后点一下地面创建路径点后就会导致服务器崩溃。
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
Fixed
