### ISSUE TITLE
[1.18.2] 初次启动无法正常启动

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [Luohuayu/CatServer#886]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): CatServer-1.18.2-edda1229-server
相关模组/插件: 无

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.guizhanss.net/9dnFY

**导致的问题r**
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 12 out of bounds for object array[11]
        at java.base/java.lang.System.arraycopy(Native Method)
        at foxlaunch.FoxServerLauncher.main(FoxServerLauncher.java:57)
**复现方法**
启动服务器..
**截图/视频**
(如果没有可以忽略)

**Comment by Thexiaoyuqaq** [comment]
java使用：zulu17 zulu18
尝试从构建站回退好几个版本问题依旧

**Comment by Kotori0629** [comment]
扬了你的-nogui 这样的参数
