### ISSUE TITLE
Can not load plugin rpgitem-reloaded

### ISSUE THREAD

**Issue by williambacteria** [Luohuayu/CatServer#89]
Because rpgitem-reloaded need NyaaCore to run.The problem is catserver may cannot load NyaaCore. Crashes as follows:

[17:04:47] [Server thread/ERROR] [Minecraft]: Could not load 'plugins\NyaaCore-v4.1.62-mc1.12.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: LangUtils
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:218) [SimplePluginManager.class:git-CatServerAsync-1.12.2-d43597b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServerAsync-1.12.2-d43597b]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:328) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[17:04:49] [Server thread/ERROR] [Minecraft]: Could not load 'plugins\rpgitem-reloaded-1.12-v.276.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: NyaaCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:218) [SimplePluginManager.class:git-CatServerAsync-1.12.2-d43597b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServerAsync-1.12.2-d43597b]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:328) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

Thanks

**Comment by williambacteria** [comment]
new crash:

[18:04:40] [Server thread/INFO]: William_Bacteria issued server command: /rpgitem
[18:04:40] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rpgitem' in plugin RPGItems v3.6.276
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServerAsync-1.12.2-d43597b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServerAsync-1.12.2-d43597b]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:709) ~[CraftServer.class:git-CatServerAsync-1.12.2-d43597b]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at think.rpgitems.commands.RPGCommandReceiver.onCommand(RPGCommandReceiver.java:169) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServerAsync-1.12.2-d43597b]
        ... 15 more

**Comment by Iltotore** [comment]
Please post the full stacktrace using hastebin

**Comment by Luohuayu** [comment]
Not a catserver problem
